-- Attendance context is resolved from server time and the congregation calendar.
create schema if not exists ca_private;
create table if not exists public.ca_meeting_settings(cong_id text primary key references public.congregations(id) on delete cascade,timezone text not null,midweek_day integer not null check(midweek_day between 0 and 6),weekend_day integer not null check(weekend_day between 0 and 6),check(midweek_day<>weekend_day));
create table if not exists public.ca_meeting_calendar(cong_id text references public.congregations(id) on delete cascade,meeting_date date not null,kind text not null check(kind in('midweek','weekend','CA','RC','Memorial')),primary key(cong_id,meeting_date));
create table if not exists public.ca_memorial_attendance(cong_id text references public.congregations(id) on delete cascade,meeting_date date not null,service_year integer generated always as (extract(year from meeting_date)::integer+case when extract(month from meeting_date)>=9 then 1 else 0 end) stored,attendance integer not null check(attendance between 0 and 99999),primary key(cong_id,meeting_date));
do $$declare t text;begin foreach t in array array['ca_meeting_settings','ca_meeting_calendar','ca_memorial_attendance'] loop execute format('alter table public.%I enable row level security',t);execute format('revoke all on public.%I from anon',t);execute format('grant select,insert,update,delete on public.%I to authenticated',t);if not exists(select 1 from pg_policies where schemaname='public' and tablename=t and policyname='attendance_section_access') then execute format('create policy attendance_section_access on public.%I to authenticated using(public.ca_has_role(cong_id,array[''attendance''])) with check(public.ca_has_role(cong_id,array[''attendance'']))',t);end if;end loop;end $$;
create or replace function ca_private.current_meeting(p_cong text) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare s public.ca_meeting_settings;d date;k text;y integer;m integer;w integer;c text;
begin select * into s from public.ca_meeting_settings where cong_id=p_cong;if s.cong_id is null then return jsonb_build_object('configured',false,'message','Ask your attendance overseer to set the meeting days and timezone.');end if;
d=(now() at time zone s.timezone)::date;select kind into k from public.ca_meeting_calendar where cong_id=p_cong and meeting_date=d;if k is null then k=case when extract(dow from d)=s.midweek_day then 'midweek' when extract(dow from d)=s.weekend_day then 'weekend' end;end if;
y=extract(year from d)::integer+case when extract(month from d)>=9 then 1 else 0 end;m=extract(month from d)::integer-1;w=least(5,((extract(day from d)::integer-1)/7)+1);
if k='Memorial' then select attendance::text into c from public.ca_memorial_attendance where cong_id=p_cong and meeting_date=d;elsif k in('midweek','weekend') then execute format('select %I from public.meeting_attendance where cong_id=$1 and service_year=$2 and month=$3','w'||w||case when k='midweek' then '_mid' else '_end' end) into c using p_cong,y,m;end if;
return jsonb_build_object('configured',true,'date',d,'kind',k,'serviceYear',y,'month',m,'week',w,'timezone',s.timezone,'count',case when c ~ '^[0-9]{1,5}$' then c::integer else null end,'canSubmit',coalesce(k in('midweek','weekend','Memorial'),false));end $$;
revoke all on function ca_private.current_meeting(text) from public,anon,authenticated;
create or replace function public.get_attendance_meeting(p_token text) returns jsonb language plpgsql stable security definer set search_path='' as $$declare l public.ca_public_links;begin l=public.ca_resolve_link(p_token,'attendance');if l.token is null then raise exception 'Invalid or withdrawn attendance link' using errcode='42501';end if;return ca_private.current_meeting(l.cong_id);end $$;
create or replace function public.submit_current_attendance(p_token text,p_date date,p_count integer) returns boolean language plpgsql security definer set search_path='' as $$
declare l public.ca_public_links;ctx jsonb;y integer;m integer;w integer;k text;
begin l=public.ca_resolve_link(p_token,'attendance');if l.token is null then raise exception 'Invalid or withdrawn attendance link' using errcode='42501';end if;ctx=ca_private.current_meeting(l.cong_id);if coalesce((ctx->>'canSubmit')::boolean,false) is not true then raise exception 'No attendance entry is scheduled for today';end if;if p_date is distinct from (ctx->>'date')::date then raise exception 'The meeting date changed. Reload the form.';end if;if p_count is null or p_count<0 or p_count>99999 then raise exception 'Enter a whole count from 0 to 99999';end if;
y=(ctx->>'serviceYear')::integer;m=(ctx->>'month')::integer;w=(ctx->>'week')::integer;k=ctx->>'kind';
if k='Memorial' then insert into public.ca_memorial_attendance(cong_id,meeting_date,attendance) values(l.cong_id,p_date,p_count) on conflict(cong_id,meeting_date) do update set attendance=excluded.attendance;return true;end if;
insert into public.meeting_attendance(id,cong_id,service_year,month) values(l.cong_id||'_'||y||'_'||m,l.cong_id,y,m) on conflict(cong_id,service_year,month) do nothing;
execute format('update public.meeting_attendance set %I=$1 where cong_id=$2 and service_year=$3 and month=$4','w'||w||case when k='midweek' then '_mid' else '_end' end) using p_count::text,l.cong_id,y,m;return true;end $$;
-- Retire the unrestricted public edit API: old clients can only save today's one field.
create or replace function public.submit_public_attendance(p_token text,p_year integer,p_month integer,p_changes jsonb) returns boolean language plpgsql security definer set search_path='' as $$
declare ctx jsonb;k text;v text;begin ctx=public.get_attendance_meeting(p_token);k='w'||(ctx->>'week')||case when ctx->>'kind'='midweek' then '_mid' when ctx->>'kind'='weekend' then '_end' else '' end;
if coalesce(ctx->>'kind','') not in('midweek','weekend') or p_year is distinct from (ctx->>'serviceYear')::integer or p_month is distinct from (ctx->>'month')::integer or jsonb_typeof(p_changes) is distinct from 'object' or (select count(*) from jsonb_object_keys(p_changes))<>1 or not p_changes ? k then raise exception 'Meeting context is locked. Reload the attendance form.';end if;v=p_changes->>k;if v is null or v !~ '^[0-9]{1,5}$' then raise exception 'A numeric attendance count is required';end if;return public.submit_current_attendance(p_token,(ctx->>'date')::date,v::integer);end $$;
create or replace function public.get_attendance_calendar(p_cong_id text) returns jsonb language plpgsql stable security definer set search_path='' as $$begin if not public.ca_has_role(p_cong_id,array['attendance']) then raise exception 'Attendance access required' using errcode='42501';end if;return jsonb_build_object('settings',(select to_jsonb(s)-'cong_id' from public.ca_meeting_settings s where cong_id=p_cong_id),'events',(select coalesce(jsonb_agg(to_jsonb(e)-'cong_id' order by meeting_date desc),'[]') from public.ca_meeting_calendar e where cong_id=p_cong_id),'memorials',(select coalesce(jsonb_agg(to_jsonb(a)-'cong_id' order by meeting_date desc),'[]') from public.ca_memorial_attendance a where cong_id=p_cong_id));end $$;
create or replace function public.save_meeting_calendar(p_cong_id text,p_timezone text,p_midweek integer,p_weekend integer,p_date date default null,p_kind text default null) returns boolean language plpgsql security definer set search_path='' as $$begin if not public.ca_has_role(p_cong_id,array['attendance']) then raise exception 'Attendance access required' using errcode='42501';end if;if not exists(select 1 from pg_timezone_names where name=p_timezone) then raise exception 'Choose a valid timezone';end if;insert into public.ca_meeting_settings values(p_cong_id,p_timezone,p_midweek,p_weekend) on conflict(cong_id) do update set timezone=excluded.timezone,midweek_day=excluded.midweek_day,weekend_day=excluded.weekend_day;if p_date is not null then if p_kind='remove' then delete from public.ca_meeting_calendar where cong_id=p_cong_id and meeting_date=p_date;else insert into public.ca_meeting_calendar values(p_cong_id,p_date,p_kind) on conflict(cong_id,meeting_date) do update set kind=excluded.kind;end if;end if;return true;end $$;
create or replace function public.save_memorial_attendance(p_cong_id text,p_date date,p_count integer) returns boolean language plpgsql security definer set search_path='' as $$begin if not public.ca_has_role(p_cong_id,array['attendance']) then raise exception 'Attendance access required' using errcode='42501';end if;insert into public.ca_memorial_attendance(cong_id,meeting_date,attendance) values(p_cong_id,p_date,p_count) on conflict(cong_id,meeting_date) do update set attendance=excluded.attendance;return true;end $$;
revoke all on function public.get_attendance_meeting(text),public.submit_current_attendance(text,date,integer),public.submit_public_attendance(text,integer,integer,jsonb),public.get_attendance_calendar(text),public.save_meeting_calendar(text,text,integer,integer,date,text),public.save_memorial_attendance(text,date,integer) from public,anon,authenticated;
grant execute on function public.get_attendance_meeting(text),public.submit_current_attendance(text,date,integer),public.submit_public_attendance(text,integer,integer,jsonb) to anon,authenticated;
grant execute on function public.get_attendance_calendar(text),public.save_meeting_calendar(text,text,integer,integer,date,text),public.save_memorial_attendance(text,date,integer) to authenticated;
