-- Additive split: retain the original OCLM JSON and IDs as a rollback source.
begin;
create table if not exists ca_private.department_publication_history(cong_id text not null references public.congregations(id) on delete cascade,department text not null,week text not null,version bigint not null,snapshot jsonb not null,created_at timestamptz not null default now(),actor uuid,primary key(cong_id,department,week,version));
alter table ca_private.department_publication_history enable row level security;
revoke all on ca_private.department_publication_history from public,anon,authenticated;
insert into ca_private.department_publication_history(cong_id,department,week,version,snapshot,created_at,actor) select cong_id,department,week,version,snapshot,updated_at,actor from ca_private.department_publications on conflict do nothing;
create table if not exists ca_private.department_workspaces(cong_id text not null references public.congregations(id) on delete cascade,department text not null check(department in('av','attendant','cleaning')),revision bigint not null default 1,data jsonb not null,updated_at timestamptz not null default now(),actor uuid,primary key(cong_id,department));
alter table ca_private.department_workspaces enable row level security;
revoke all on ca_private.department_workspaces from public,anon,authenticated;
insert into ca_private.department_workspaces(cong_id,department,data)
select r.cong_id,r.department,jsonb_build_object('duties',(select coalesce(jsonb_agg(d),'[]') from jsonb_array_elements(w.data->'additionalDuties') d join ca_private.department_duties dr on dr.cong_id=r.cong_id and dr.department=r.department and dr.id=d->>'id'),'assignments',(select coalesce(jsonb_object_agg(week.key,(select coalesce(jsonb_object_agg(a.key,a.value||jsonb_build_object('publisherId',coalesce(p->>'publisherId',p->>'id'),'name',p->>'name')),'{}') from jsonb_each(week.value) a join ca_private.department_duties dr on dr.cong_id=r.cong_id and dr.department=r.department and dr.id=regexp_replace(a.key,'_[1-4]$','') left join lateral(select person p from jsonb_array_elements(w.data->'personnel') person where person->>'id'=a.value->>'personId' limit 1) person on true)),'{}') from jsonb_each(w.data->'assignments') week),'events','{}'::jsonb)
from(select distinct cong_id,department from ca_private.department_duties) r join public.ca_oclm_workspaces w on w.cong_id=r.cong_id on conflict do nothing;
create or replace function ca_private.ensure_department_workspace(p_cong text,p_department text) returns void language plpgsql security definer set search_path='' as $$begin
insert into ca_private.department_workspaces(cong_id,department,data) values(p_cong,p_department,jsonb_build_object('duties','[]'::jsonb,'assignments','{}'::jsonb,'events','{}'::jsonb)) on conflict do nothing;end $$;
revoke all on function ca_private.ensure_department_workspace(text,text) from public,anon,authenticated;
create or replace function ca_private.can_publish_department(p_cong text,p_department text) returns boolean language sql stable security definer set search_path='' as $$select ca_private.can_manage_department(p_cong,p_department) and (public.ca_is_congregation_admin(p_cong) or public.ca_is_superadmin() or exists(select 1 from public.congregation_access a where a.cong_id=p_cong and a.active and a.email=lower(auth.jwt()->>'email') and not a.is_assistant and a.role=any(case when p_department='attendant' then array['attendance','attendant'] when p_department='av' then array['av'] when p_department='cleaning' then array['cleaning'] else array[]::text[] end)));$$;
revoke all on function ca_private.can_publish_department(text,text) from public,anon,authenticated;
create or replace function public.get_department_workspace(p_cong_id text,p_department text) returns jsonb language plpgsql stable security definer set search_path='' as $$declare w ca_private.department_workspaces;draft jsonb;begin
if not ca_private.can_manage_department(p_cong_id,p_department) then raise exception 'Department access required' using errcode='42501';end if;
select * into w from ca_private.department_workspaces where cong_id=p_cong_id and department=p_department;select data into draft from public.ca_oclm_workspaces where cong_id=p_cong_id;
return jsonb_build_object('revision',coalesce(w.revision,0),'canPublish',ca_private.can_publish_department(p_cong_id,p_department),'duties',coalesce(w.data->'duties','[]'),'assignments',coalesce(w.data->'assignments','{}'),'events',coalesce(w.data->'events','{}'),'meetingSettings',(select jsonb_build_object('midweekDay',midweek_day,'weekendDay',weekend_day,'timezone',timezone) from public.ca_meeting_settings where cong_id=p_cong_id),'publicationVersions',(select coalesce(jsonb_object_agg(week,version),'{}') from ca_private.department_publications where cong_id=p_cong_id and department=p_department),'publishedAt',(select coalesce(jsonb_object_agg(week,updated_at),'{}') from ca_private.department_publications where cong_id=p_cong_id and department=p_department),'token',(select token from public.ca_oclm_publications where cong_id=p_cong_id),'people',(select coalesce(jsonb_agg(jsonb_build_object('id',p.id,'name',p.name,'status',coalesce(e.status,'not_requested'),'availability',coalesce((select person->'availability' from jsonb_array_elements(coalesce(draft->'personnel','[]')) person where person->>'publisherId'=p.id or person->>'id'=p.id limit 1),'[]'),'busyDates',(select coalesce(jsonb_agg(distinct (event.value->>'date')||'|'||(event.value->>'session')),'[]') from ca_private.department_workspaces other cross join lateral jsonb_each(other.data->'events') event cross join lateral jsonb_each(event.value->'assignments') a where other.cong_id=p_cong_id and other.department<>p_department and a.value->>'publisherId'=p.id)) order by p.name),'[]') from public.publishers p left join ca_private.department_people e on e.cong_id=p.cong_id and e.publisher_id=p.id and e.department=p_department where p.cong_id=p_cong_id and p.transferred_at is null));end $$;
create or replace function public.save_department_duty(p_cong_id text,p_department text,p_expected_revision bigint,p_id text,p_name text,p_slots integer,p_enabled boolean default true) returns jsonb language plpgsql security definer set search_path='' as $$declare w ca_private.department_workspaces;id_value text;d jsonb;duties jsonb;begin
if not ca_private.can_manage_department(p_cong_id,p_department) then raise exception 'Department access required' using errcode='42501';end if;
if p_name is null or length(trim(p_name)) not between 1 and 100 or p_slots is null or p_slots not between 1 and 4 or p_enabled is null then raise exception 'Enter a duty name and 1 to 4 people';end if;
perform pg_advisory_xact_lock(hashtextextended('department:'||p_cong_id||':'||p_department,0));select * into w from ca_private.department_workspaces where cong_id=p_cong_id and department=p_department;
if p_expected_revision is distinct from coalesce(w.revision,0) then raise exception 'This department changed. Reload and review before saving.' using errcode='40001';end if;
perform ca_private.ensure_department_workspace(p_cong_id,p_department);select * into w from ca_private.department_workspaces where cong_id=p_cong_id and department=p_department;
id_value=coalesce(p_id,'Duty_'||replace(gen_random_uuid()::text,'-',''));if id_value !~ '^Duty_[a-f0-9]{32}$' or p_id is not null and not exists(select 1 from ca_private.department_duties where cong_id=p_cong_id and department=p_department and id=p_id) then raise exception 'Duty is outside this department' using errcode='42501';end if;
if p_id is null and jsonb_array_length(w.data->'duties')>=20 then raise exception 'Up to 20 duties per department';end if;
if exists(select 1 from jsonb_array_elements(w.data->'duties') x where x->>'id'<>id_value and lower(trim(x->>'name'))=lower(trim(p_name))) then raise exception 'That duty already exists';end if;
if exists(select 1 from(select value assignment from jsonb_each(w.data->'assignments') union all select e.value->'assignments' from jsonb_each(w.data->'events') e) weeks cross join lateral jsonb_each(assignment) a where a.key like id_value||'_%' and substring(a.key from '_([1-4])$')::integer>p_slots and nullif(a.value->>'publisherId','') is not null) then raise exception 'Keep assigned places or clear them before reducing the number';end if;
d=jsonb_build_object('id',id_value,'name',trim(p_name),'section',case p_department when 'av' then 'Audio Video Department' when 'attendant' then 'Attendant (Attendance Department)' else 'Cleaning' end,'slots',p_slots,'enabled',p_enabled);
select coalesce(jsonb_agg(x),'[]') into duties from jsonb_array_elements(w.data->'duties') x where x->>'id'<>id_value;duties=duties||jsonb_build_array(d);
insert into ca_private.department_duties(cong_id,id,department) values(p_cong_id,id_value,p_department) on conflict do nothing;
update ca_private.department_workspaces set data=jsonb_set(data,'{duties}',duties),revision=w.revision+1,updated_at=clock_timestamp(),actor=auth.uid() where cong_id=p_cong_id and department=p_department;
return public.get_department_workspace(p_cong_id,p_department);end $$;
create or replace function public.save_department_assignments(p_cong_id text,p_department text,p_expected_revision bigint,p_week text,p_assignments jsonb) returns jsonb language plpgsql security definer set search_path='' as $$declare w ca_private.department_workspaces;assigned jsonb;part record;p public.publishers;duty jsonb;draft jsonb;begin
if not ca_private.can_manage_department(p_cong_id,p_department) then raise exception 'Department access required' using errcode='42501';end if;
if p_week is null or p_week !~ '^[0-9]{4}-W(0[1-9]|[1-4][0-9]|5[0-3])$' or jsonb_typeof(p_assignments) is distinct from 'object' or (select count(*) from jsonb_object_keys(p_assignments))>80 then raise exception 'Check week and assignments';end if;
perform pg_advisory_xact_lock(hashtextextended('department:'||p_cong_id||':'||p_department,0));select * into w from ca_private.department_workspaces where cong_id=p_cong_id and department=p_department;
if w.cong_id is null or p_expected_revision is distinct from w.revision then raise exception 'This department changed. Reload and review before saving.' using errcode='40001';end if;
assigned=coalesce(w.data->'assignments'->p_week,'{}');select data into draft from public.ca_oclm_workspaces where cong_id=p_cong_id;
for part in select * from jsonb_each_text(p_assignments) loop
select x into duty from jsonb_array_elements(w.data->'duties') x where x->>'id'=regexp_replace(part.key,'_[1-4]$','');if duty is null or part.key !~ '^Duty_[a-f0-9]{32}_[1-4]$' or substring(part.key from '_([1-4])$')::integer>(duty->>'slots')::integer then raise exception 'Assignment is outside this department' using errcode='42501';end if;
if coalesce(part.value,'')='' then assigned=assigned||jsonb_build_object(part.key,jsonb_build_object('personId',null,'publisherId',null,'status','scheduled'));continue;end if;
select * into p from public.publishers where cong_id=p_cong_id and id=part.value and transferred_at is null;if p.id is null then raise exception 'Choose an active publisher in this congregation' using errcode='42501';end if;
if not exists(select 1 from ca_private.department_people where cong_id=p_cong_id and department=p_department and publisher_id=p.id and status='approved') then raise exception 'Main administrator approval required' using errcode='42501';end if;
if exists(select 1 from jsonb_array_elements(coalesce(draft->'personnel','[]')) person cross join lateral jsonb_array_elements(coalesce(person->'availability','[]')) away where (person->>'publisherId'=p.id or person->>'id'=p.id) and to_date(p_week||'-1','IYYY-"W"IW-ID')<=(away->>'to')::date and to_date(p_week||'-7','IYYY-"W"IW-ID')>=(away->>'from')::date) then raise exception 'This publisher is unavailable that week';end if;
assigned=assigned||jsonb_build_object(part.key,jsonb_build_object('personId',p.id,'publisherId',p.id,'name',p.name,'status','scheduled'));end loop;
update ca_private.department_workspaces set data=jsonb_set(data,array['assignments',p_week],assigned),revision=w.revision+1,updated_at=clock_timestamp(),actor=auth.uid() where cong_id=p_cong_id and department=p_department;
return public.get_department_workspace(p_cong_id,p_department);end $$;
create or replace function public.publish_department_week(p_cong_id text,p_department text,p_week text,p_expected_revision bigint,p_expected_version bigint) returns jsonb language plpgsql security definer set search_path='' as $$declare w ca_private.department_workspaces;old ca_private.department_publications;duties jsonb;assigned jsonb;people jsonb;events jsonb;snapshot jsonb;begin
if not ca_private.can_publish_department(p_cong_id,p_department) then raise exception 'Department publisher access required; assistants cannot publish' using errcode='42501';end if;
if p_week is null or p_week !~ '^[0-9]{4}-W(0[1-9]|[1-4][0-9]|5[0-3])$' then raise exception 'Choose a valid week';end if;
perform pg_advisory_xact_lock(hashtextextended('oclm:'||p_cong_id,0));perform pg_advisory_xact_lock(hashtextextended('department:'||p_cong_id||':'||p_department,0));select * into w from ca_private.department_workspaces where cong_id=p_cong_id and department=p_department;select * into old from ca_private.department_publications where cong_id=p_cong_id and department=p_department and week=p_week;
if w.cong_id is null or p_expected_revision is distinct from w.revision or p_expected_version is distinct from coalesce(old.version,0) then raise exception 'Department changed. Reload and review before publishing.' using errcode='40001';end if;
select coalesce(jsonb_agg(d),'[]') into duties from jsonb_array_elements(w.data->'duties') d where coalesce((d->>'enabled')::boolean,true);if jsonb_array_length(duties)=0 then raise exception 'Add an enabled duty first';end if;
assigned=coalesce(w.data->'assignments'->p_week,'{}');select coalesce(jsonb_object_agg(e.key,e.value),'{}') into events from jsonb_each(w.data->'events') e where e.value->>'week'=p_week;
if events<>'{}'::jsonb then raise exception 'Date-specific duties need a separate review before publishing';end if;
if exists(select 1 from(select assigned records union all select e.value->'assignments' from jsonb_each(events) e) all_records cross join lateral jsonb_each(records) a left join public.publishers p on p.cong_id=p_cong_id and p.id=a.value->>'publisherId' where nullif(a.value->>'publisherId','') is not null and (p.id is null or p.transferred_at is not null or not exists(select 1 from ca_private.department_people elig where elig.cong_id=p_cong_id and elig.department=p_department and elig.publisher_id=p.id and elig.status='approved'))) then raise exception 'Review publisher eligibility before publishing' using errcode='42501';end if;
select coalesce(jsonb_agg(person),'[]') into people from(select distinct jsonb_build_object('id',a.value->>'personId','name',a.value->>'name') person from(select assigned records union all select e.value->'assignments' from jsonb_each(events) e) all_records cross join lateral jsonb_each(records) a where nullif(a.value->>'personId','') is not null) x;
snapshot=jsonb_build_object('duties',duties,'assignments',assigned,'events',events,'people',people,'source',p_department,'sourceRevision',w.revision);
insert into ca_private.department_publications(cong_id,department,week,version,snapshot,updated_at,actor) values(p_cong_id,p_department,p_week,coalesce(old.version,0)+1,snapshot,clock_timestamp(),auth.uid()) on conflict(cong_id,department,week) do update set snapshot=excluded.snapshot,version=excluded.version,updated_at=excluded.updated_at,actor=excluded.actor;
insert into ca_private.department_publication_history(cong_id,department,week,version,snapshot,actor) values(p_cong_id,p_department,p_week,coalesce(old.version,0)+1,snapshot,auth.uid());
perform pg_advisory_xact_lock(hashtextextended('oclm:'||p_cong_id,0));perform set_config('ca.skip_publication_mail','true',true);
insert into public.ca_oclm_publications(cong_id,version,snapshot) values(p_cong_id,0,jsonb_build_object('v',2,'kind','midweek','publishedWeeks','[]'::jsonb,'assignments','{}'::jsonb,'people','[]'::jsonb)) on conflict(cong_id) do update set updated_at=clock_timestamp();perform set_config('ca.skip_publication_mail','false',true);
return public.get_department_workspace(p_cong_id,p_department);end $$;
revoke all on function public.save_department_assignments(text,text,bigint,text,jsonb) from public,anon,authenticated;
grant execute on function public.save_department_assignments(text,text,bigint,text,jsonb) to authenticated;
commit;
