-- Verified-Google requests and transactional mail. No anonymous form/mail relay.
create table if not exists ca_private.trial_requests(id uuid primary key default gen_random_uuid(),user_id uuid unique not null references auth.users(id) on delete cascade,email text not null,congregation_name text not null check(length(congregation_name) between 2 and 150),created_at timestamptz not null default now(),cong_id text references public.congregations(id) on delete set null,status text not null default 'pending' check(status in('pending','approved')));
create table if not exists ca_private.workspace_mail(cong_id text primary key references public.congregations(id) on delete cascade,email text not null,enabled boolean not null default false,published boolean not null default true,reports boolean not null default true,oclm boolean not null default true,oclm_day integer not null default 1 check(oclm_day between 0 and 6),reminder_time time not null default '09:00',timezone text not null default 'Asia/Kolkata');
alter table ca_private.workspace_mail add column if not exists attendance boolean not null default false;alter table ca_private.workspace_mail add column if not exists attendance_link boolean not null default false;alter table ca_private.workspace_mail add column if not exists attendance_time time not null default '21:00';alter table ca_private.workspace_mail add column if not exists attendance_link_time time not null default '17:00';
create table if not exists ca_private.mail_outbox(id uuid primary key default gen_random_uuid(),dedupe text unique not null,email text not null,subject text not null,body text not null,created_at timestamptz not null default now(),available_at timestamptz not null default now(),state text not null default 'queued' check(state in('queued','sending','sent','failed')),attempts integer not null default 0,lease uuid,provider_id text,sent_at timestamptz);
create index if not exists mail_due_idx on ca_private.mail_outbox(available_at) where state in('queued','sending');
alter table ca_private.trial_requests enable row level security;alter table ca_private.workspace_mail enable row level security;alter table ca_private.mail_outbox enable row level security;
revoke all on ca_private.trial_requests,ca_private.workspace_mail,ca_private.mail_outbox from public,anon,authenticated;
create or replace function public.request_congregation_trial(p_name text,p_authorized boolean) returns jsonb language plpgsql security definer set search_path='' as $$declare e text;r ca_private.trial_requests;begin
if not public.ca_google_identity() or p_authorized is distinct from true or not exists(select 1 from auth.users where id=auth.uid() and email_confirmed_at is not null) then raise exception 'Sign in with Google and confirm congregation authorization' using errcode='42501';end if;
e=lower(auth.jwt()->>'email');if length(trim(p_name)) not between 2 and 150 then raise exception 'Enter a congregation name from 2 to 150 characters';end if;
insert into ca_private.trial_requests(user_id,email,congregation_name) values(auth.uid(),e,trim(p_name)) on conflict(user_id) do nothing;select * into r from ca_private.trial_requests where user_id=auth.uid();
insert into ca_private.mail_outbox(dedupe,email,subject,body) values('request:'||r.id,e,'Your Congregation Assistant request','Your request has been recorded for '||r.congregation_name||'. Your reference is '||r.id||'. The setup owner will review authorization and assign the congregation ID. There is no payment or charge. Help: https://photographicode.github.io/Congregation-Assistant_Public/how-to-use.html') on conflict(dedupe) do nothing;
return jsonb_build_object('reference',r.id,'status',r.status,'emailQueued',true);end $$;
create or replace function public.get_trial_requests() returns jsonb language plpgsql stable security definer set search_path='' as $$begin if not public.ca_is_superadmin() then raise exception 'Owner access required' using errcode='42501';end if;return(select coalesce(jsonb_agg(to_jsonb(r)-'user_id' order by created_at),'[]') from ca_private.trial_requests r where status='pending');end $$;
create or replace function ca_private.approve_requested_workspace() returns trigger language plpgsql security definer set search_path='' as $$declare r ca_private.trial_requests;begin if new.role='admin' and new.active then for r in select * from ca_private.trial_requests where email=lower(new.email) and status='pending' loop update ca_private.trial_requests set status='approved',cong_id=new.cong_id where id=r.id;insert into ca_private.mail_outbox(dedupe,email,subject,body) values('welcome:'||r.id,r.email,'Your Congregation Assistant workspace is ready','Your congregation ID is '||new.cong_id||'. Continue with Google using this email: https://photographicode.github.io/congregation-assistant/staging/index.html . Your administrator can assign Service, OCLM and Attendance roles. Guide: https://photographicode.github.io/Congregation-Assistant_Public/how-to-use.html . Your trial does not create an automatic charge.') on conflict(dedupe) do nothing;end loop;end if;return new;end $$;
drop trigger if exists approve_requested_workspace on public.congregation_access;create trigger approve_requested_workspace after insert or update on public.congregation_access for each row execute function ca_private.approve_requested_workspace();
create or replace function public.set_workspace_email(p_cong_id text,p_email text,p_enabled boolean,p_published boolean,p_reports boolean,p_oclm boolean,p_day integer,p_time time,p_timezone text) returns boolean language plpgsql security definer set search_path='' as $$begin
if not public.ca_is_congregation_admin(p_cong_id) then raise exception 'Main administrator access required' using errcode='42501';end if;
if not exists(select 1 from public.congregation_access a join auth.users u on lower(u.email)=lower(a.email) where a.cong_id=p_cong_id and a.role='admin' and a.active and lower(a.email)=lower(trim(p_email)) and u.email_confirmed_at is not null and u.raw_app_meta_data->>'provider'='google') then raise exception 'Choose a main administrator email that has already signed in with Google';end if;
if not exists(select 1 from pg_timezone_names where name=p_timezone) then raise exception 'Choose a valid timezone';end if;
insert into ca_private.workspace_mail(cong_id,email,enabled,published,reports,oclm,oclm_day,reminder_time,timezone) values(p_cong_id,lower(trim(p_email)),p_enabled,p_published,p_reports,p_oclm,p_day,p_time,p_timezone) on conflict(cong_id) do update set email=excluded.email,enabled=excluded.enabled,published=excluded.published,reports=excluded.reports,oclm=excluded.oclm,oclm_day=excluded.oclm_day,reminder_time=excluded.reminder_time,timezone=excluded.timezone;return true;end $$;
create or replace function public.set_attendance_email(p_cong_id text,p_enabled boolean,p_link boolean,p_time time,p_link_time time) returns boolean language plpgsql security definer set search_path='' as $$begin if not public.ca_is_congregation_admin(p_cong_id) then raise exception 'Main administrator access required' using errcode='42501';end if;update ca_private.workspace_mail set attendance=p_enabled,attendance_link=p_link,attendance_time=p_time,attendance_link_time=p_link_time where cong_id=p_cong_id;if not found then raise exception 'Save the verified congregation email first';end if;return true;end $$;
create or replace function public.get_workspace_email(p_cong_id text) returns jsonb language plpgsql stable security definer set search_path='' as $$begin if not public.ca_is_congregation_admin(p_cong_id) then raise exception 'Main administrator access required' using errcode='42501';end if;return(select to_jsonb(s)-'cong_id' from ca_private.workspace_mail s where cong_id=p_cong_id);end $$;
create or replace function ca_private.notify_publication() returns trigger language plpgsql security definer set search_path='' as $$declare s ca_private.workspace_mail;begin select * into s from ca_private.workspace_mail where cong_id=new.cong_id and enabled and published;if s.cong_id is not null then insert into ca_private.mail_outbox(dedupe,email,subject,body) values('published:'||new.cong_id||':'||new.updated_at,s.email,'Meeting schedule published','A meeting schedule was published for your congregation. Open your approved workspace to review it. No publisher names or private records are included in this email.');end if;return new;end $$;
drop trigger if exists notify_publication on public.ca_oclm_publications;create trigger notify_publication after insert or update on public.ca_oclm_publications for each row execute function ca_private.notify_publication();
create or replace function public.claim_transactional_mail() returns jsonb language plpgsql security definer set search_path='' as $$declare s ca_private.workspace_mail;local_now timestamp;kind text;limit_count integer;result jsonb;begin
if auth.role() is distinct from 'service_role' then raise exception 'Mail worker access required' using errcode='42501';end if;
for s in select m.* from ca_private.workspace_mail m join public.congregations c on c.id=m.cong_id where m.enabled and(c.status='active' or c.status='trial' and c.created_at+c.trial_days*interval '1 day'>now()) and exists(select 1 from public.congregation_access a where a.cong_id=m.cong_id and a.email=m.email and a.role='admin' and a.active) loop
local_now=now() at time zone s.timezone;
foreach kind in array array['reports','oclm','attendance','attendance_link'] loop
if (kind='reports' and s.reports and extract(day from local_now)=1 and local_now::time>=s.reminder_time) or (kind='oclm' and s.oclm and extract(dow from local_now)=s.oclm_day and local_now::time>=s.reminder_time) or (kind='attendance' and s.attendance and local_now::time>=s.attendance_time and coalesce((ca_private.current_meeting(s.cong_id)->>'canSubmit')::boolean,false)) or (kind='attendance_link' and s.attendance_link and local_now::time>=s.attendance_link_time and coalesce((ca_private.current_meeting(s.cong_id)->>'canSubmit')::boolean,false)) then
insert into ca_private.mail_outbox(dedupe,email,subject,body) values('reminder:'||s.cong_id||':'||kind||':'||local_now::date,s.email,case when kind='reports' then 'Service reports: previous month' when kind='attendance' then 'Record today’s meeting attendance' when kind='attendance_link' then 'Share today’s attendance form' else 'OCLM: plan three weeks ahead' end,case when kind='reports' then 'Collect the previous month’s reports in your assigned workspace.' when kind='attendance' then 'Open Attendance, record today’s meeting count and confirm the save. Memorial counts are stored separately.' when kind='attendance_link' then 'Open Attendance and share the approved form link with the person counting today. This email does not contain the form token.' else 'Assign and review the meeting week three weeks ahead. Publish after checking the schedule.' end||' Open your approved Congregation Assistant workspace. This message contains no personal records.') on conflict(dedupe) do nothing;end if;end loop;end loop;
limit_count=greatest(0,least(20,250-(select count(*) from ca_private.mail_outbox where sent_at>=date_trunc('day',now()) or state='sending' and available_at>now())));
with due as(select id from ca_private.mail_outbox where (state='queued' and available_at<=now() or state='sending' and available_at<=now()) and attempts<5 order by available_at for update skip locked limit limit_count), claimed as(update ca_private.mail_outbox m set state='sending',lease=gen_random_uuid(),attempts=attempts+1,available_at=now()+interval '15 minutes' from due where m.id=due.id returning m.id,m.email,m.subject,m.body,m.lease) select coalesce(jsonb_agg(to_jsonb(c)),'[]') into result from claimed c;return result;end $$;
create or replace function public.finish_transactional_mail(p_id uuid,p_lease uuid,p_provider_id text) returns boolean language plpgsql security definer set search_path='' as $$begin if auth.role() is distinct from 'service_role' then raise exception 'Mail worker access required' using errcode='42501';end if;update ca_private.mail_outbox set state=case when p_provider_id is not null then 'sent' when attempts>=5 then 'failed' else 'queued' end,provider_id=p_provider_id,sent_at=case when p_provider_id is not null then now() else null end,available_at=now()+interval '30 minutes',lease=null where id=p_id and lease=p_lease and state='sending';return found;end $$;
revoke all on function ca_private.approve_requested_workspace(),ca_private.notify_publication() from public,anon,authenticated;
revoke all on function public.request_congregation_trial(text,boolean),public.get_trial_requests(),public.set_workspace_email(text,text,boolean,boolean,boolean,boolean,integer,time,text),public.get_workspace_email(text),public.set_attendance_email(text,boolean,boolean,time,time),public.claim_transactional_mail(),public.finish_transactional_mail(uuid,uuid,text) from public,anon,authenticated;
grant execute on function public.request_congregation_trial(text,boolean),public.get_trial_requests(),public.set_workspace_email(text,text,boolean,boolean,boolean,boolean,integer,time,text),public.get_workspace_email(text),public.set_attendance_email(text,boolean,boolean,time,time) to authenticated;
grant execute on function public.claim_transactional_mail(),public.finish_transactional_mail(uuid,uuid,text) to service_role;
