-- Approved-account publisher APIs. No new direct private-table grants.
create table if not exists ca_private.publisher_preferences (
 cong_id text not null, publisher_id text not null, revision bigint not null default 0,
 reminders jsonb not null default '[]', updated_at timestamptz not null default now(),
 primary key(cong_id,publisher_id), foreign key(publisher_id,cong_id) references public.publishers(id,cong_id) on delete cascade
);
alter table ca_private.publisher_preferences enable row level security;
revoke all on ca_private.publisher_preferences from public,anon,authenticated;
create or replace function ca_private.my_publisher(p_cong text) returns text language plpgsql stable security definer set search_path='' as $$declare pid text;begin
 if auth.uid() is null or not public.ca_google_identity() or not exists(select 1 from auth.users u where u.id=auth.uid() and u.email_confirmed_at is not null and lower(u.email)=lower(auth.jwt()->>'email')) or not public.ca_has_role(p_cong,array['publisher']) then raise exception 'Sign in with your approved Google account.' using errcode='42501';end if;
 select p.id into pid from public.congregation_access a join public.publishers p on p.cong_id=a.cong_id and p.id=a.publisher_id where a.cong_id=p_cong and a.active and a.role='publisher' and a.email=lower(auth.jwt()->>'email') and p.transferred_at is null;
 if pid is null then raise exception 'Ask your administrator to connect this Google account to your publisher record.' using errcode='42501';end if;return pid;
end $$;
create or replace function ca_private.publisher_contact(p public.publishers) returns jsonb language sql immutable set search_path='' as $$select jsonb_build_object('phone',coalesce(p.phone,''),'address',coalesce(p.address,''),'emergency_name',coalesce(p.emergency_name,''),'emergency_relationship',coalesce(p.emergency_relationship,''),'emergency_phone',coalesce(p.emergency_phone,''));$$;
create or replace function ca_private.publisher_attendance(p_cong text,p_id text) returns jsonb language plpgsql stable security definer set search_path='' as $$declare ctx jsonb;current_week text;begin
 ctx=ca_private.current_meeting(p_cong);current_week=to_char((ctx->>'date')::date,'IYYY-"W"IW');
 if coalesce((ctx->>'canSubmit')::boolean,false) and exists(select 1 from ca_private.department_publications d cross join lateral jsonb_each(coalesce(d.snapshot->'assignments','{}')) a where d.cong_id=p_cong and d.department='attendant' and d.week=current_week and coalesce(a.value->>'publisherId',a.value->>'personId')=p_id and coalesce(a.value->>'status','scheduled')<>'cancelled' and exists(select 1 from ca_private.department_people e where e.cong_id=p_cong and e.department='attendant' and e.publisher_id=p_id and e.status='approved')) then return ctx;end if;return null;
end $$;
create or replace function public.get_my_publisher_portal(p_cong_id text) returns jsonb language plpgsql stable security definer set search_path='' as $$declare pid text;p public.publishers;w jsonb;snapshot jsonb;away jsonb;own_ids text[];assignments jsonb;h jsonb;begin
 pid=ca_private.my_publisher(p_cong_id);select * into p from public.publishers where cong_id=p_cong_id and id=pid;
 h=public.get_my_publisher_home(p_cong_id);select data into w from public.ca_oclm_workspaces where cong_id=p_cong_id;select ca_private.noticeboard_snapshot(p_cong_id,pub.snapshot) into snapshot from public.ca_oclm_publications pub where pub.cong_id=p_cong_id;
 select coalesce(jsonb_agg(a),'[]') into away from (select distinct x a from jsonb_array_elements(coalesce(w->'personnel','[]')) person cross join lateral jsonb_array_elements(coalesce(person->'availability','[]')) x where person->>'publisherId'=pid or person->>'id'=pid) periods;
 select coalesce(array_agg(person->>'id'),'{}')||array[pid] into own_ids from jsonb_array_elements(coalesce(w->'personnel','[]')) person where person->>'publisherId'=pid or person->>'id'=pid;
 select coalesce(jsonb_agg(jsonb_build_object('week',week.key,'slot',a.key,'title',coalesce(nullif(a.value->>'customTitle',''),(select d->>'name' from jsonb_array_elements(coalesce(snapshot->'weekDetails'->week.key->'additionalDuties','[]')) d where a.key like (d->>'id')||'_%' limit 1),(select part->>'title' from jsonb_array_elements(coalesce(snapshot->'weekDetails'->week.key->'program'->'parts','[]')) part where part->>'id'=a.key limit 1),a.key),'department',(select r.department from ca_private.department_duties r where r.cong_id=p_cong_id and r.id=regexp_replace(a.key,'_[1-4]$','')),'date',to_date(week.key||'-1','IYYY-"W"IW-ID')+coalesce((select midweek_day from public.ca_meeting_settings where cong_id=p_cong_id)+6,9)%7) order by week.key,a.key),'[]') into assignments from jsonb_each(coalesce(snapshot->'assignments','{}')) week cross join lateral jsonb_each(week.value) a where a.value->>'personId'=any(own_ids) and coalesce(a.value->>'status','scheduled')<>'cancelled';
 return h||jsonb_build_object('assignments',assignments,'schedule',snapshot,'contact',ca_private.publisher_contact(p),'away',away,'scheduleRevision',coalesce((select revision from public.ca_oclm_workspaces where cong_id=p_cong_id),0),'reminders',coalesce((select reminders from ca_private.publisher_preferences where cong_id=p_cong_id and publisher_id=pid),'[]'),'preferencesRevision',coalesce((select revision from ca_private.publisher_preferences where cong_id=p_cong_id and publisher_id=pid),0),'attendance',ca_private.publisher_attendance(p_cong_id,pid),'timezone',coalesce((select timezone from public.ca_meeting_settings where cong_id=p_cong_id),'Asia/Kolkata'));
end $$;
create or replace function public.update_my_publisher_contact(p_cong_id text,p_expected jsonb,p_contact jsonb) returns jsonb language plpgsql security definer set search_path='' as $$declare pid text;p public.publishers;v text;k text;begin
 pid=ca_private.my_publisher(p_cong_id);select * into p from public.publishers where cong_id=p_cong_id and id=pid for update;
 if p_expected is distinct from ca_private.publisher_contact(p) then raise exception 'Your contact details changed on another device. Copy your edits, then refresh and review.' using errcode='40001';end if;
 if jsonb_typeof(p_contact) is distinct from 'object' or pg_column_size(p_contact)>8192 or exists(select 1 from jsonb_object_keys(p_contact) x where x<>all(array['phone','address','emergency_name','emergency_relationship','emergency_phone'])) or (select count(*) from jsonb_object_keys(p_contact))<>5 then raise exception 'Only your contact fields can be changed';end if;
 foreach k in array array['phone','address','emergency_name','emergency_relationship','emergency_phone'] loop v=p_contact->>k;if jsonb_typeof(p_contact->k)<>'string' or length(v)>(case when k='address' then 2000 else 200 end) then raise exception 'Check the contact fields';end if;end loop;
 update public.publishers set phone=trim(p_contact->>'phone'),address=trim(p_contact->>'address'),emergency_name=trim(p_contact->>'emergency_name'),emergency_relationship=trim(p_contact->>'emergency_relationship'),emergency_phone=trim(p_contact->>'emergency_phone') where cong_id=p_cong_id and id=pid returning * into p;
 return ca_private.publisher_contact(p);
end $$;
create or replace function public.save_my_publisher_away(p_cong_id text,p_expected_revision bigint,p_away jsonb) returns jsonb language plpgsql security definer set search_path='' as $$declare pid text;w public.ca_oclm_workspaces;p public.publishers;period jsonb;clean jsonb='[]';people jsonb;data jsonb;begin
 pid=ca_private.my_publisher(p_cong_id);if jsonb_typeof(p_away) is distinct from 'array' or jsonb_array_length(p_away)>50 then raise exception 'Choose up to 50 away periods';end if;
 for period in select value from jsonb_array_elements(p_away) loop if coalesce(period->>'from','') !~ '^\d{4}-\d{2}-\d{2}$' or coalesce(period->>'to','') !~ '^\d{4}-\d{2}-\d{2}$' or (period->>'from')::date>(period->>'to')::date then raise exception 'Choose the first and last away dates';end if;clean=clean||jsonb_build_array(jsonb_build_object('from',period->>'from','to',period->>'to'));end loop;
 perform pg_advisory_xact_lock(hashtextextended('oclm:'||p_cong_id,0));select * into w from public.ca_oclm_workspaces where cong_id=p_cong_id;
 if p_expected_revision is distinct from coalesce(w.revision,0) then raise exception 'The schedule changed. Your dates are still here. Refresh and review before saving.' using errcode='40001';end if;
 data=coalesce(w.data,jsonb_build_object('v',3,'personnel','[]'::jsonb,'assignments','{}'::jsonb,'programs','{}'::jsonb,'additionalDuties','[]'::jsonb,'template','modern'));
 select coalesce(jsonb_agg(case when person->>'publisherId'=pid or person->>'id'=pid then person||jsonb_build_object('availability',clean) else person end),'[]') into people from jsonb_array_elements(data->'personnel') person;
 if not exists(select 1 from jsonb_array_elements(people) person where person->>'publisherId'=pid or person->>'id'=pid) then select * into p from public.publishers where cong_id=p_cong_id and id=pid;people=people||jsonb_build_array(jsonb_build_object('id',pid,'publisherId',pid,'name',p.name,'gender',p.gender,'appointment',case when p.is_elder then 'Elder' when p.is_ms then 'MS' when p.gender='Female' then 'Sister' else 'Other' end,'availability',clean,'roles','[]'::jsonb,'exceptions','{}'::jsonb,'archived',false));end if;
 data=jsonb_set(data,'{personnel}',people);
 insert into public.ca_oclm_workspaces(cong_id,revision,data,updated_at,updated_by) values(p_cong_id,coalesce(w.revision,0)+1,data,clock_timestamp(),auth.uid()) on conflict(cong_id) do update set revision=excluded.revision,data=excluded.data,updated_at=excluded.updated_at,updated_by=excluded.updated_by;
 return jsonb_build_object('away',clean,'scheduleRevision',coalesce(w.revision,0)+1);
end $$;
create or replace function public.save_my_publisher_reminders(p_cong_id text,p_expected_revision bigint,p_reminders jsonb) returns jsonb language plpgsql security definer set search_path='' as $$declare pid text;revision bigint;item jsonb;clean jsonb='[]';begin
 pid=ca_private.my_publisher(p_cong_id);if jsonb_typeof(p_reminders) is distinct from 'array' or jsonb_array_length(p_reminders)>12 then raise exception 'Up to 12 personal reminders';end if;
 for item in select value from jsonb_array_elements(p_reminders) loop if coalesce(item->>'id','') !~ '^[A-Za-z0-9_-]{1,80}$' or length(trim(coalesce(item->>'title',''))) not between 1 and 100 or coalesce(item->>'date','') !~ '^\d{4}-\d{2}-\d{2}$' or coalesce(item->>'time','') !~ '^([01][0-9]|2[0-3]):[0-5][0-9]$' then raise exception 'Choose a title, date and time';end if;perform (item->>'date')::date;clean=clean||jsonb_build_array(jsonb_build_object('id',item->>'id','title',trim(item->>'title'),'date',item->>'date','time',item->>'time'));end loop;
 perform pg_advisory_xact_lock(hashtextextended('publisher-preferences:'||p_cong_id||':'||pid,0));select p.revision into revision from ca_private.publisher_preferences p where p.cong_id=p_cong_id and p.publisher_id=pid;
 if p_expected_revision is distinct from coalesce(revision,0) then raise exception 'Reminders changed on another device. Your edits are kept; refresh and review.' using errcode='40001';end if;
 insert into ca_private.publisher_preferences(cong_id,publisher_id,revision,reminders) values(p_cong_id,pid,coalesce(revision,0)+1,clean) on conflict(cong_id,publisher_id) do update set revision=excluded.revision,reminders=excluded.reminders,updated_at=clock_timestamp();return jsonb_build_object('reminders',clean,'preferencesRevision',coalesce(revision,0)+1);
end $$;
create or replace function public.submit_my_attendance(p_cong_id text,p_date date,p_count integer,p_expected_count integer) returns boolean language plpgsql security definer set search_path='' as $$declare pid text;ctx jsonb;y integer;m integer;w integer;k text;begin
 pid=ca_private.my_publisher(p_cong_id);perform pg_advisory_xact_lock(hashtextextended('publisher-attendance:'||p_cong_id,0));ctx=ca_private.publisher_attendance(p_cong_id,pid);
 if ctx is null or p_date is distinct from (ctx->>'date')::date then raise exception 'This form is only for your assigned meeting today. Refresh, or ask the attendance overseer.' using errcode='42501';end if;
 if p_count is null or p_count<0 or p_count>99999 then raise exception 'Enter a whole count from 0 to 99999';end if;
 y=(ctx->>'serviceYear')::integer;m=(ctx->>'month')::integer;
 if ctx->>'kind'<>'Memorial' then insert into public.meeting_attendance(id,cong_id,service_year,month) values(p_cong_id||'_'||y||'_'||m,p_cong_id,y,m) on conflict(cong_id,service_year,month) do nothing;perform 1 from public.meeting_attendance where cong_id=p_cong_id and service_year=y and month=m for update;ctx=ca_private.publisher_attendance(p_cong_id,pid);end if;
 if p_expected_count is distinct from (ctx->>'count')::integer then raise exception 'Today’s count changed. Keep your count and refresh before correcting it.' using errcode='40001';end if;
 y=(ctx->>'serviceYear')::integer;m=(ctx->>'month')::integer;w=(ctx->>'week')::integer;k=ctx->>'kind';
 if k='Memorial' then insert into public.ca_memorial_attendance(cong_id,meeting_date,attendance) values(p_cong_id,p_date,p_count) on conflict(cong_id,meeting_date) do update set attendance=excluded.attendance where ca_memorial_attendance.attendance is not distinct from p_expected_count;if not found then raise exception 'Today’s count changed. Refresh before correcting it.' using errcode='40001';end if;else
 insert into public.meeting_attendance(id,cong_id,service_year,month) values(p_cong_id||'_'||y||'_'||m,p_cong_id,y,m) on conflict(cong_id,service_year,month) do nothing;
 execute format('update public.meeting_attendance set %I=$1 where cong_id=$2 and service_year=$3 and month=$4','w'||w||case when k='midweek' then '_mid' else '_end' end) using p_count::text,p_cong_id,y,m;end if;return true;
end $$;
revoke all on function ca_private.my_publisher(text),ca_private.publisher_contact(public.publishers),ca_private.publisher_attendance(text,text) from public,anon,authenticated;
revoke all on function public.get_my_publisher_portal(text),public.update_my_publisher_contact(text,jsonb,jsonb),public.save_my_publisher_away(text,bigint,jsonb),public.save_my_publisher_reminders(text,bigint,jsonb),public.submit_my_attendance(text,date,integer,integer) from public,anon,authenticated;
grant execute on function public.get_my_publisher_portal(text),public.update_my_publisher_contact(text,jsonb,jsonb),public.save_my_publisher_away(text,bigint,jsonb),public.save_my_publisher_reminders(text,bigint,jsonb),public.submit_my_attendance(text,date,integer,integer) to authenticated;
-- Prepared queue producer: requires the existing private worker; does not activate delivery.
create or replace function public.queue_publisher_reminders() returns integer language plpgsql security definer set search_path='' as $$declare recipient record;item jsonb;board jsonb;own_ids text[];week record;slot record;local_time timestamp;event_date date;added integer=0;rows integer;begin
 if auth.role() is distinct from 'service_role' then raise exception 'Private worker required' using errcode='42501';end if;
 delete from ca_private.push_outbox j using ca_private.push_subscriptions s where j.subscription_id=s.id and j.dedupe like 'publisher:%' and j.delivered_at is null and not exists(select 1 from public.congregation_access a join public.publishers p on p.cong_id=a.cong_id and p.id=a.publisher_id where a.cong_id=s.cong_id and a.email=s.email and a.role='publisher' and a.active and p.transferred_at is null);
 for recipient in select s.id,s.cong_id,s.preferences,p.id publisher_id,pref.reminders,coalesce((select timezone from public.ca_meeting_settings where cong_id=s.cong_id),'Asia/Kolkata') timezone from ca_private.push_subscriptions s join public.congregation_access a on a.cong_id=s.cong_id and a.email=s.email and a.active and a.role='publisher' join public.publishers p on p.cong_id=a.cong_id and p.id=a.publisher_id and p.transferred_at is null join public.congregations c on c.id=s.cong_id join auth.users u on u.id=s.user_id and lower(u.email)=s.email and u.email_confirmed_at is not null left join ca_private.publisher_preferences pref on pref.cong_id=p.cong_id and pref.publisher_id=p.id where c.status='active' or c.status='trial' and c.created_at+c.trial_days*interval '1 day'>now() loop
 local_time=now() at time zone recipient.timezone;
 for item in select value from jsonb_array_elements(coalesce(recipient.reminders,'[]')) loop if (item->>'date')::date=local_time::date and local_time::time>=(item->>'time')::time then insert into ca_private.push_outbox(subscription_id,dedupe,title,body) values(recipient.id,'publisher:personal:'||recipient.id||':'||(item->>'id')||':'||md5(item::text),'Personal reminder','A personal reminder is due. Open My Home to check it.') on conflict(dedupe) do nothing;get diagnostics rows=row_count;added=added+rows;end if;end loop;
 if coalesce((recipient.preferences->>'assignments')::boolean,true) and local_time::time>='09:00'::time then
 select ca_private.noticeboard_snapshot(p.cong_id,p.snapshot) into board from public.ca_oclm_publications p where p.cong_id=recipient.cong_id;
 select coalesce(array_agg(person->>'id'),'{}')||array[recipient.publisher_id] into own_ids from public.ca_oclm_workspaces w cross join lateral jsonb_array_elements(coalesce(w.data->'personnel','[]')) person where w.cong_id=recipient.cong_id and (person->>'publisherId'=recipient.publisher_id or person->>'id'=recipient.publisher_id);
 for week in select * from jsonb_each(coalesce(board->'assignments','{}')) loop event_date=to_date(week.key||'-1','IYYY-"W"IW-ID')+coalesce((select midweek_day+6 from public.ca_meeting_settings where cong_id=recipient.cong_id),9)%7;
 if event_date=local_time::date+1 then for slot in select * from jsonb_each(week.value) loop if slot.value->>'personId'=any(own_ids) and coalesce(slot.value->>'status','scheduled')<>'cancelled' then insert into ca_private.push_outbox(subscription_id,dedupe,title,body) values(recipient.id,'publisher:assignment:'||recipient.id||':'||week.key||':'||slot.key,'Upcoming assignment','You have a published assignment or duty tomorrow. Open My Home to check it.') on conflict(dedupe) do nothing;get diagnostics rows=row_count;added=added+rows;end if;end loop;end if;end loop;
 end if;end loop;return added;
end $$;
revoke all on function public.queue_publisher_reminders() from public,anon,authenticated;
grant execute on function public.queue_publisher_reminders() to service_role;

-- Recovery includes personal reminders; older backup formats remain compatible.
create or replace function public.export_congregation_workspace(p_cong_id text) returns jsonb language plpgsql stable security definer set search_path='' as $$declare payload jsonb;begin
if not public.ca_is_congregation_admin(p_cong_id) then raise exception 'Main administrator access required' using errcode='42501';end if;
payload=jsonb_build_object('format','ca-workspace-v1','congregation',p_cong_id,'profile',(select jsonb_build_object('name',name,'email',email,'notes',notes) from public.congregations where id=p_cong_id),'publishers',(select coalesce(jsonb_agg(to_jsonb(p) order by id),'[]') from public.publishers p where cong_id=p_cong_id),'reports',(select coalesce(jsonb_agg(to_jsonb(r) order by id),'[]') from public.reports r where cong_id=p_cong_id),'attendance',(select coalesce(jsonb_agg(to_jsonb(a) order by id),'[]') from public.meeting_attendance a where cong_id=p_cong_id),'meetingSettings',(select to_jsonb(s) from public.ca_meeting_settings s where cong_id=p_cong_id),'calendar',(select coalesce(jsonb_agg(to_jsonb(c) order by meeting_date),'[]') from public.ca_meeting_calendar c where cong_id=p_cong_id),'memorial',(select coalesce(jsonb_agg(to_jsonb(m) order by meeting_date),'[]') from public.ca_memorial_attendance m where cong_id=p_cong_id),'scheduler',(select data from public.ca_oclm_workspaces where cong_id=p_cong_id),'publication',(select snapshot from public.ca_oclm_publications where cong_id=p_cong_id),'publicationHistory',(select coalesce(jsonb_agg(to_jsonb(h)-'actor' order by version),'[]') from public.ca_oclm_publication_history h where cong_id=p_cong_id),'assignmentHistory',(select coalesce(jsonb_agg(to_jsonb(e)-'actor' order by id),'[]') from public.ca_oclm_assignment_events e where cong_id=p_cong_id),'access',(select coalesce(jsonb_agg(to_jsonb(a) order by id),'[]') from public.congregation_access a where cong_id=p_cong_id),'departmentPublicationHistory',(select coalesce(jsonb_agg(to_jsonb(h)-'actor' order by department,week,version),'[]') from ca_private.department_publication_history h where cong_id=p_cong_id),'departmentWorkspaces',(select coalesce(jsonb_agg(to_jsonb(dw)-'actor' order by department),'[]') from ca_private.department_workspaces dw where cong_id=p_cong_id),'departmentPublications',(select coalesce(jsonb_agg(to_jsonb(dp)-'actor' order by department,week),'[]') from ca_private.department_publications dp where cong_id=p_cong_id),'departmentDuties',(select coalesce(jsonb_agg(to_jsonb(d) order by id),'[]') from ca_private.department_duties d where cong_id=p_cong_id),'departmentPeople',(select coalesce(jsonb_agg(to_jsonb(d)-'requested_by'-'decided_by' order by department,publisher_id),'[]') from ca_private.department_people d where cong_id=p_cong_id),'emailSettings',(select to_jsonb(s) from ca_private.workspace_mail s where cong_id=p_cong_id));
payload=payload||jsonb_build_object('publisherPreferences',(select coalesce(jsonb_agg(to_jsonb(p) order by publisher_id),'[]') from ca_private.publisher_preferences p where cong_id=p_cong_id));
return jsonb_build_object('data',payload,'fingerprint',md5(payload::text));end $$;
create or replace function public.restore_congregation_workspace(p_cong_id text,p_expected_fingerprint text,p_backup jsonb) returns boolean language plpgsql security definer set search_path='' as $$declare current_backup jsonb;old_revision bigint;old_version bigint;restored jsonb;item jsonb;rowvalue jsonb;pub public.ca_oclm_publications;layouts jsonb='{}';meeting_week record;clean_layout jsonb;begin
if not public.ca_is_congregation_admin(p_cong_id) then raise exception 'Main administrator access required' using errcode='42501';end if;
perform pg_advisory_xact_lock(hashtextextended('oclm:'||p_cong_id,0));lock table public.publishers,public.reports,public.meeting_attendance,public.congregation_access,public.ca_meeting_settings,public.ca_meeting_calendar,public.ca_memorial_attendance in share row exclusive mode;
current_backup=public.export_congregation_workspace(p_cong_id);if p_expected_fingerprint is distinct from current_backup->>'fingerprint' then raise exception 'Workspace changed. Export its latest recovery copy before restoring.' using errcode='40001';end if;
if p_backup->>'format' is distinct from 'ca-workspace-v1' or p_backup->>'congregation' is distinct from p_cong_id or pg_column_size(p_backup)>33554432 then raise exception 'Choose a valid backup for this congregation';end if;
foreach rowvalue in array array[p_backup->'publishers',p_backup->'reports',p_backup->'attendance',p_backup->'calendar',p_backup->'memorial',p_backup->'access'] loop if jsonb_typeof(rowvalue) is distinct from 'array' then raise exception 'Backup datasets are incomplete';end if;end loop;
-- Preserve billing, public-link tokens and current membership grants. They are reviewed separately.
-- Publisher grants survive when their publisher IDs remain; omitted IDs remove those grants by FK.
set constraints all deferred;
delete from public.reports where cong_id=p_cong_id;delete from public.meeting_attendance where cong_id=p_cong_id;
-- Update existing publishers without deleting their bindings; insert absent records, remove omitted ones.
for item in select value from jsonb_array_elements(p_backup->'publishers') loop if item->>'cong_id' is distinct from p_cong_id then raise exception 'Foreign congregation record';end if;if exists(select 1 from public.publishers where id=item->>'id' and cong_id<>p_cong_id) then raise exception 'Foreign publisher ID' using errcode='42501';end if;
insert into public.publishers select (jsonb_populate_record(null::public.publishers,item||jsonb_build_object('is_infirm',coalesce((item->>'is_infirm')::boolean,false),'is_sfts',coalesce((item->>'is_sfts')::boolean,false)))).* on conflict(id) do update set name=excluded.name,service_group=case when publishers.transferred_at is not null then null else excluded.service_group end,gender=excluded.gender,hope=excluded.hope,dob=excluded.dob,baptized=excluded.baptized,is_elder=excluded.is_elder,is_ms=excluded.is_ms,is_rp=excluded.is_rp,is_sp=excluded.is_sp,is_fm=excluded.is_fm,phone=excluded.phone,address=excluded.address,emergency_name=excluded.emergency_name,emergency_relationship=excluded.emergency_relationship,emergency_phone=excluded.emergency_phone,spiritual_status=excluded.spiritual_status,family_head_id=excluded.family_head_id,is_infirm=excluded.is_infirm,is_sfts=excluded.is_sfts,transferred_at=coalesce(publishers.transferred_at,excluded.transferred_at);end loop;
delete from public.publishers where cong_id=p_cong_id and not exists(select 1 from jsonb_array_elements(p_backup->'publishers') p where p->>'id'=publishers.id);
for item in select value from jsonb_array_elements(p_backup->'reports') loop if item->>'cong_id' is distinct from p_cong_id then raise exception 'Foreign report';end if;insert into public.reports select (jsonb_populate_record(null::public.reports,item)).*;end loop;
for item in select value from jsonb_array_elements(p_backup->'attendance') loop if item->>'cong_id' is distinct from p_cong_id then raise exception 'Foreign attendance';end if;insert into public.meeting_attendance select (jsonb_populate_record(null::public.meeting_attendance,item)).*;end loop;
delete from public.ca_meeting_calendar where cong_id=p_cong_id;delete from public.ca_memorial_attendance where cong_id=p_cong_id;
for item in select value from jsonb_array_elements(p_backup->'calendar') loop if item->>'cong_id' is distinct from p_cong_id then raise exception 'Foreign meeting';end if;insert into public.ca_meeting_calendar select (jsonb_populate_record(null::public.ca_meeting_calendar,item)).*;end loop;
for item in select value from jsonb_array_elements(p_backup->'memorial') loop if item->>'cong_id' is distinct from p_cong_id then raise exception 'Foreign memorial record';end if;insert into public.ca_memorial_attendance(cong_id,meeting_date,attendance) values(p_cong_id,(item->>'meeting_date')::date,(item->>'attendance')::integer);end loop;
if jsonb_typeof(p_backup->'meetingSettings')='object' then item=p_backup->'meetingSettings';if item->>'cong_id' is distinct from p_cong_id or not exists(select 1 from pg_timezone_names where name=item->>'timezone') then raise exception 'Invalid meeting settings';end if;insert into public.ca_meeting_settings select (jsonb_populate_record(null::public.ca_meeting_settings,item)).* on conflict(cong_id) do update set timezone=excluded.timezone,midweek_day=excluded.midweek_day,weekend_day=excluded.weekend_day;else delete from public.ca_meeting_settings where cong_id=p_cong_id;end if;
select revision into old_revision from public.ca_oclm_workspaces where cong_id=p_cong_id;select version into old_version from public.ca_oclm_publications where cong_id=p_cong_id;
if p_backup ? 'departmentDuties' then
if jsonb_typeof(p_backup->'departmentDuties') is distinct from 'array' or jsonb_typeof(p_backup->'departmentPeople') is distinct from 'array' then raise exception 'Invalid department backup';end if;
delete from ca_private.department_duties where cong_id=p_cong_id;delete from ca_private.department_people where cong_id=p_cong_id;
for item in select value from jsonb_array_elements(p_backup->'departmentDuties') loop if item->>'cong_id' is distinct from p_cong_id or not exists(select 1 from jsonb_array_elements(coalesce(p_backup->'scheduler'->'additionalDuties','[]')||(select coalesce(jsonb_agg(d),'[]') from jsonb_array_elements(coalesce(p_backup->'departmentWorkspaces','[]')) dw cross join lateral jsonb_array_elements(dw->'data'->'duties') d)) d where d->>'id'=item->>'id') then raise exception 'Invalid department duty';end if;insert into ca_private.department_duties(cong_id,id,department) values(p_cong_id,item->>'id',item->>'department');end loop;
for item in select value from jsonb_array_elements(p_backup->'departmentPeople') loop if item->>'cong_id' is distinct from p_cong_id then raise exception 'Foreign department approval';end if;insert into ca_private.department_people(cong_id,department,publisher_id,status,decided_by) values(p_cong_id,item->>'department',item->>'publisher_id',item->>'status',auth.uid());end loop;
else
-- Legacy files do not revoke present eligibility approvals. Remove only orphan ownership definitions.
delete from ca_private.department_duties r where r.cong_id=p_cong_id and not exists(select 1 from jsonb_array_elements(coalesce(p_backup->'scheduler'->'additionalDuties','[]')) d where d->>'id'=r.id);
end if;
perform set_config('ca.restoring_departments','true',true);
if jsonb_typeof(p_backup->'scheduler')='object' then restored=public.save_oclm_workspace(p_cong_id,coalesce(old_revision,0),p_backup->'scheduler');end if;perform set_config('ca.restoring_departments','false',true);
if jsonb_typeof(p_backup->'publication')='object' then perform set_config('ca.skip_publication_mail','true',true);perform public.upsert_oclm_public_snapshot(p_cong_id,p_backup->'publication');perform set_config('ca.skip_publication_mail','false',true);
for meeting_week in select * from jsonb_each(coalesce(p_backup->'publication'->'weekDetails','{}')) loop clean_layout=ca_private.clean_oclm_draft(p_cong_id,jsonb_build_object('personnel','[]'::jsonb,'assignments','{}'::jsonb,'additionalDuties',coalesce(meeting_week.value->'additionalDuties','[]'),'programs',case when jsonb_typeof(meeting_week.value->'program')='object' then jsonb_build_object(meeting_week.key,meeting_week.value->'program') else '{}'::jsonb end));layouts=layouts||jsonb_build_object(meeting_week.key,jsonb_build_object('additionalDuties',clean_layout->'additionalDuties','program',clean_layout->'programs'->meeting_week.key));end loop;
update public.ca_oclm_publications set snapshot=snapshot||jsonb_build_object('weekDetails',layouts),version=coalesce(old_version,0)+1,updated_at=clock_timestamp() where cong_id=p_cong_id returning * into pub;insert into public.ca_oclm_publication_history(cong_id,version,snapshot,action,actor) values(p_cong_id,pub.version,pub.snapshot,'restore_workspace',auth.uid());end if;
if jsonb_typeof(p_backup->'emailSettings')='object' then item=p_backup->'emailSettings';perform public.set_workspace_email(p_cong_id,item->>'email',(item->>'enabled')::boolean,(item->>'published')::boolean,(item->>'reports')::boolean,(item->>'oclm')::boolean,(item->>'oclm_day')::integer,(item->>'reminder_time')::time,item->>'timezone');perform public.set_attendance_email(p_cong_id,(item->>'attendance')::boolean,(item->>'attendance_link')::boolean,(item->>'attendance_time')::time,(item->>'attendance_link_time')::time);else delete from ca_private.workspace_mail where cong_id=p_cong_id;end if;
update public.congregations set name=left(p_backup->'profile'->>'name',150),email=left(p_backup->'profile'->>'email',254),notes=left(p_backup->'profile'->>'notes',10000) where id=p_cong_id;
if p_backup ? 'departmentWorkspaces' then
if jsonb_typeof(p_backup->'departmentWorkspaces') is distinct from 'array' or jsonb_array_length(p_backup->'departmentWorkspaces')>3 then raise exception 'Invalid department workspaces';end if;
for item in select value from jsonb_array_elements(p_backup->'departmentWorkspaces') loop
if item->>'cong_id' is distinct from p_cong_id or jsonb_typeof(item->'data'->'duties') is distinct from 'array' or jsonb_typeof(item->'data'->'assignments') is distinct from 'object' then raise exception 'Invalid department workspace';end if;
if exists(select 1 from jsonb_array_elements(item->'data'->'duties') d where not exists(select 1 from ca_private.department_duties ownership where ownership.cong_id=p_cong_id and ownership.department=item->>'department' and ownership.id=d->>'id')) then raise exception 'Backup duty belongs outside its department';end if;
if exists(select 1 from jsonb_each(item->'data'->'assignments') week cross join lateral jsonb_each(week.value) a where nullif(a.value->>'publisherId','') is not null and not exists(select 1 from public.publishers p where p.cong_id=p_cong_id and p.id=a.value->>'publisherId')) then raise exception 'Backup assignment is outside this congregation';end if;
-- A reviewed older backup cannot restore future assignments for a publisher already transferred.
item=jsonb_set(item,'{data,assignments}',(select coalesce(jsonb_object_agg(week.key,case when week.key<to_char(now() at time zone coalesce((select timezone from public.ca_meeting_settings where cong_id=p_cong_id),'Asia/Kolkata'),'IYYY-"W"IW') then week.value else (select coalesce(jsonb_object_agg(a.key,case when exists(select 1 from public.publishers p where p.cong_id=p_cong_id and p.id=a.value->>'publisherId' and p.transferred_at is not null) then jsonb_build_object('personId',null,'publisherId',null,'status','cancelled') else a.value end),'{}') from jsonb_each(week.value) a) end),'{}') from jsonb_each(item->'data'->'assignments') week));
perform pg_advisory_xact_lock(hashtextextended('department:'||p_cong_id||':'||(item->>'department'),0));
insert into ca_private.department_workspaces(cong_id,department,data,revision,actor) values(p_cong_id,item->>'department',item->'data',1,auth.uid()) on conflict(cong_id,department) do update set data=excluded.data,revision=department_workspaces.revision+1,updated_at=clock_timestamp(),actor=auth.uid();end loop;end if;
if p_backup ? 'departmentPublications' then
if jsonb_typeof(p_backup->'departmentPublications') is distinct from 'array' or jsonb_array_length(p_backup->'departmentPublications')>1560 then raise exception 'Invalid published department backup';end if;
delete from ca_private.department_publications where cong_id=p_cong_id;
for item in select value from jsonb_array_elements(p_backup->'departmentPublications') loop if item->>'cong_id' is distinct from p_cong_id or jsonb_typeof(item->'snapshot') is distinct from 'object' then raise exception 'Invalid department publication';end if;insert into ca_private.department_publications(cong_id,department,week,version,snapshot,actor) values(p_cong_id,item->>'department',item->>'week',greatest(coalesce((item->>'version')::bigint,0),coalesce((select max(version) from ca_private.department_publication_history where cong_id=p_cong_id and department=item->>'department' and week=item->>'week'),0))+1,item->'snapshot',auth.uid());end loop;end if;
if p_backup ? 'departmentPublicationHistory' then
if jsonb_typeof(p_backup->'departmentPublicationHistory') is distinct from 'array' then raise exception 'Invalid department publication history';end if;
for item in select value from jsonb_array_elements(p_backup->'departmentPublicationHistory') loop
if item->>'cong_id' is distinct from p_cong_id or item->>'department' not in('av','attendant','cleaning') or jsonb_typeof(item->'snapshot') is distinct from 'object' then raise exception 'Invalid department publication history';end if;
insert into ca_private.department_publication_history(cong_id,department,week,version,snapshot,actor) values(p_cong_id,item->>'department',item->>'week',(item->>'version')::bigint,item->'snapshot',auth.uid()) on conflict do nothing;end loop;end if;
insert into ca_private.department_publication_history(cong_id,department,week,version,snapshot,actor) select cong_id,department,week,version,snapshot,auth.uid() from ca_private.department_publications where cong_id=p_cong_id on conflict do nothing;
if p_backup ? 'publisherPreferences' then
 if jsonb_typeof(p_backup->'publisherPreferences') is distinct from 'array' then raise exception 'Invalid publisher reminder backup';end if;
 for item in select value from jsonb_array_elements(p_backup->'publisherPreferences') loop
 if item->>'cong_id' is distinct from p_cong_id or jsonb_typeof(item->'reminders') is distinct from 'array' or jsonb_array_length(item->'reminders')>12 or not exists(select 1 from public.publishers where cong_id=p_cong_id and id=item->>'publisher_id') then raise exception 'Invalid or foreign publisher reminder backup';end if;
 if exists(select 1 from jsonb_array_elements(item->'reminders') r where coalesce(r->>'id','') !~ '^[A-Za-z0-9_-]{1,80}$' or length(trim(coalesce(r->>'title',''))) not between 1 and 100 or coalesce(r->>'date','') !~ '^\d{4}-\d{2}-\d{2}$' or coalesce(r->>'time','') !~ '^([01][0-9]|2[0-3]):[0-5][0-9]$') then raise exception 'Invalid reminder entry in backup';end if;
 insert into ca_private.publisher_preferences(cong_id,publisher_id,reminders,revision) values(p_cong_id,item->>'publisher_id',item->'reminders',1) on conflict(cong_id,publisher_id) do update set reminders=excluded.reminders,revision=publisher_preferences.revision+1,updated_at=clock_timestamp();
 end loop;
 -- Older backups keep current reminders for retained publishers. New backups restore their explicit reminder dataset.
 delete from ca_private.publisher_preferences p where p.cong_id=p_cong_id and not exists(select 1 from jsonb_array_elements(p_backup->'publisherPreferences') x where x->>'publisher_id'=p.publisher_id);
end if;
return true;end $$;
