-- A publisher grant is bound to exactly one publisher in the same congregation.
alter table public.congregation_access drop constraint if exists congregation_access_role_check;
alter table public.congregation_access add constraint congregation_access_role_check check(role in('admin','field_service','attendance','oclm','group_overseer','publisher'));
alter table public.congregation_access add column if not exists publisher_id text;
alter table public.congregation_access add constraint ca_access_publisher_fk foreign key(publisher_id,cong_id) references public.publishers(id,cong_id) on delete cascade;
alter table public.congregation_access add constraint ca_access_publisher_required check((role='publisher')=(publisher_id is not null));
create index ca_access_publisher_idx on public.congregation_access(publisher_id,cong_id);
alter policy congregations_read on public.congregations using(public.ca_has_role(id,array['admin','field_service','attendance','oclm','group_overseer','publisher']));
create or replace function public.get_my_publisher_home(p_cong_id text) returns jsonb language plpgsql stable security definer set search_path='' as $$declare p public.publishers;draft jsonb;snap jsonb;own_ids text[];assignments jsonb;previous date=(date_trunc('month',now() at time zone 'Asia/Kolkata')-interval '1 month')::date;sy integer;mo integer;report jsonb;begin
if not public.ca_has_role(p_cong_id,array['publisher']) then raise exception 'Publisher access required' using errcode='42501';end if;
select publisher.* into p from public.publishers publisher join public.congregation_access a on a.publisher_id=publisher.id and a.cong_id=publisher.cong_id where a.active and a.role='publisher' and a.email=lower(auth.jwt()->>'email') and a.cong_id=p_cong_id;
if p.id is null then raise exception 'Your publisher record is not assigned. Ask your administrator.' using errcode='42501';end if;
select data into draft from public.ca_oclm_workspaces where cong_id=p_cong_id;select snapshot into snap from public.ca_oclm_publications where cong_id=p_cong_id;
select coalesce(array_agg(person->>'id'),'{}') into own_ids from jsonb_array_elements(coalesce(draft->'personnel','[]')) person where person->>'publisherId'=p.id;
select coalesce(jsonb_agg(jsonb_build_object('week',w.key,'slot',a.key,'title',coalesce(nullif(a.value->>'customTitle',''),(select part->>'title' from jsonb_array_elements(coalesce(snap->'weekDetails'->w.key->'program'->'parts','[]')) part where part->>'id'=a.key limit 1),(select d->>'name' from jsonb_array_elements(coalesce(snap->'weekDetails'->w.key->'additionalDuties',snap->'additionalDuties','[]')) d where a.key like (d->>'id')||'_%' limit 1),a.key)) order by w.key,a.key),'[]') into assignments from jsonb_each(coalesce(snap->'assignments','{}')) w cross join lateral jsonb_each(w.value) a where a.value->>'personId'=any(own_ids);
mo=extract(month from previous)::integer-1;sy=extract(year from previous)::integer+case when mo>=8 then 1 else 0 end;
select jsonb_build_object('shared',shared_in_ministry,'studies',studies,'hours',hours,'comments',comments,'auxiliaryPioneer',is_ap) into report from public.reports where cong_id=p_cong_id and pub_id=p.id and month=mo and service_year=sy;
return jsonb_build_object('name',p.name,'assignments',assignments,'report',jsonb_build_object('period',to_char(previous,'FMMonth YYYY'),'month',mo,'serviceYear',sy,'submitted',report is not null,'record',report,'hoursRequired',coalesce(p.is_rp,false) or coalesce(p.is_sp,false) or coalesce(p.is_fm,false)),'notice',(select case when notes like '%[[CA_NOTICE]]%' then substring(notes from '\[\[CA_NOTICE\]\](.*?)\[\[/CA_NOTICE\]\]') else null end from public.congregations where id=p_cong_id));end $$;
create or replace function public.submit_my_publisher_report(p_cong_id text,p_shared boolean,p_studies integer,p_hours numeric,p_comments text,p_auxiliary boolean default false) returns jsonb language plpgsql security definer set search_path='' as $$declare home jsonb;publisher text;sy integer;mo integer;begin
home=public.get_my_publisher_home(p_cong_id);if p_shared is null or p_studies is null or p_studies<0 or p_studies>1000 or p_hours is null or p_hours<0 or p_hours>744 or length(coalesce(p_comments,''))>2000 then raise exception 'Check the report values';end if;
select publisher_id into publisher from public.congregation_access where cong_id=p_cong_id and email=lower(auth.jwt()->>'email') and role='publisher' and active;
sy=(home->'report'->>'serviceYear')::integer;mo=(home->'report'->>'month')::integer;
if not p_shared then p_studies=0;p_hours=0;p_auxiliary=false;end if;if p_hours>0 and not (home->'report'->>'hoursRequired')::boolean and not coalesce(p_auxiliary,false) then raise exception 'Hours apply to pioneers or auxiliary pioneers';end if;
insert into public.reports(id,cong_id,pub_id,service_year,month,shared_in_ministry,studies,hours,comments,is_ap) values(gen_random_uuid()::text,p_cong_id,publisher,sy,mo,p_shared,p_studies,p_hours,left(coalesce(p_comments,''),2000),coalesce(p_auxiliary,false)) on conflict(pub_id,service_year,month) do update set shared_in_ministry=excluded.shared_in_ministry,studies=excluded.studies,hours=excluded.hours,comments=excluded.comments,is_ap=excluded.is_ap;
return jsonb_build_object('saved',true,'period',home->'report'->>'period');end $$;
revoke all on function public.get_my_publisher_home(text),public.submit_my_publisher_report(text,boolean,integer,numeric,text,boolean) from public,anon,authenticated;
grant execute on function public.get_my_publisher_home(text),public.submit_my_publisher_report(text,boolean,integer,numeric,text,boolean) to authenticated;
