-- Browser endpoints and delivery queues are private. Notifications contain no personal records.
create table if not exists ca_private.push_subscriptions(id uuid primary key default gen_random_uuid(),user_id uuid not null,cong_id text not null references public.congregations(id) on delete cascade,email text not null,endpoint text not null,subscription jsonb not null,preferences jsonb not null default '{"reports":true,"oclm":true,"attendance":true}',created_at timestamptz not null default now(),unique(user_id,cong_id,endpoint));
create index push_subscriptions_cong_email_idx on ca_private.push_subscriptions(cong_id,email);
create table if not exists ca_private.push_outbox(id uuid primary key default gen_random_uuid(),subscription_id uuid not null references ca_private.push_subscriptions(id) on delete cascade,dedupe text not null unique,title text not null,body text not null,attempts integer not null default 0,next_attempt timestamptz not null default now(),lease uuid,leased_at timestamptz,delivered_at timestamptz);
create index push_outbox_pending_idx on ca_private.push_outbox(next_attempt) where delivered_at is null;
alter table ca_private.push_subscriptions enable row level security;alter table ca_private.push_outbox enable row level security;revoke all on ca_private.push_subscriptions,ca_private.push_outbox from public,anon,authenticated;
create or replace function public.register_push_subscription(p_cong_id text,p_subscription jsonb,p_preferences jsonb default '{}') returns uuid language plpgsql security definer set search_path='' as $$declare out_id uuid;rule jsonb;prefs jsonb;begin
if auth.uid() is null or not public.ca_has_role(p_cong_id,array['publisher','field_service','attendance','oclm','group_overseer']) then raise exception 'Approved Google workspace required' using errcode='42501';end if;
if (select count(*) from ca_private.push_subscriptions where user_id=auth.uid() and cong_id=p_cong_id and endpoint is distinct from p_subscription->>'endpoint')>=10 then raise exception 'Remove an old notification device before adding another';end if;
if pg_column_size(p_subscription)>8192 or coalesce(p_subscription->>'endpoint','') !~ '^https://(fcm\.googleapis\.com|updates\.push\.services\.mozilla\.com|web\.push\.apple\.com|[a-z0-9-]+\.notify\.windows\.com)/' or coalesce(p_subscription->'keys'->>'p256dh','') !~ '^[A-Za-z0-9_-]{80,120}$' or coalesce(p_subscription->'keys'->>'auth','') !~ '^[A-Za-z0-9_-]{16,40}$' then raise exception 'Unsupported or invalid browser notification endpoint';end if;
if jsonb_typeof(coalesce(p_preferences->'rules','[]'))<>'array' or jsonb_array_length(coalesce(p_preferences->'rules','[]'))>6 or not exists(select 1 from pg_timezone_names where name=coalesce(p_preferences->>'timezone','Asia/Kolkata')) then raise exception 'Check notification timezone and rules';end if;
for rule in select value from jsonb_array_elements(coalesce(p_preferences->'rules','[]')) loop if coalesce(rule->>'id','')<>all(array['reports','report_link','oclm','attendance_midweek','attendance_weekend','attendance_link']) or coalesce(rule->>'time','') !~ '^([01][0-9]|2[0-3]):[0-5][0-9]$' or jsonb_typeof(rule->'enabled')<>'boolean' or (rule->>'id' not in('reports','report_link') and coalesce(rule->>'day','') !~ '^[0-6]$') then raise exception 'Check notification times';end if;end loop;
prefs=jsonb_build_object('reports',coalesce((p_preferences->>'reports')::boolean,true),'oclm',coalesce((p_preferences->>'oclm')::boolean,true),'attendance',coalesce((p_preferences->>'attendance')::boolean,true),'assignments',coalesce((p_preferences->>'assignments')::boolean,true),'timezone',coalesce(p_preferences->>'timezone','Asia/Kolkata'),'rules',coalesce(p_preferences->'rules','[]'));
insert into ca_private.push_subscriptions(user_id,cong_id,email,endpoint,subscription,preferences) values(auth.uid(),p_cong_id,lower(auth.jwt()->>'email'),p_subscription->>'endpoint',jsonb_build_object('endpoint',p_subscription->>'endpoint','keys',p_subscription->'keys'),prefs) on conflict(user_id,cong_id,endpoint) do update set email=excluded.email,subscription=excluded.subscription,preferences=excluded.preferences returning id into out_id;return out_id;end $$;
create or replace function public.remove_push_subscription(p_endpoint text) returns boolean language plpgsql security definer set search_path='' as $$begin delete from ca_private.push_subscriptions where user_id=auth.uid() and endpoint=p_endpoint;return true;end $$;
create or replace function ca_private.queue_publication_push() returns trigger language plpgsql security definer set search_path='' as $$declare s ca_private.push_subscriptions;person_ids text[];changed boolean;begin
if current_setting('ca.skip_publication_mail',true)='true' or new.version=coalesce(old.version,0) then return new;end if;
for s in select * from ca_private.push_subscriptions where cong_id=new.cong_id and coalesce((preferences->>'assignments')::boolean,true) loop
if not public.ca_google_identity() then continue;end if;
select array_agg(person->>'id') into person_ids from public.ca_oclm_workspaces w cross join lateral jsonb_array_elements(w.data->'personnel') person join public.congregation_access a on a.publisher_id=person->>'publisherId' and a.cong_id=w.cong_id where w.cong_id=new.cong_id and a.email=s.email and a.active and a.role='publisher';
select exists(select 1 from (select w.key week,a.key slot,a.value from jsonb_each(coalesce(new.snapshot->'assignments','{}')) w cross join lateral jsonb_each(w.value) a where a.value->>'personId'=any(person_ids) except select w.key,a.key,a.value from jsonb_each(coalesce(old.snapshot->'assignments','{}')) w cross join lateral jsonb_each(w.value) a where a.value->>'personId'=any(person_ids)) added) or exists(select 1 from (select w.key week,a.key slot,a.value from jsonb_each(coalesce(old.snapshot->'assignments','{}')) w cross join lateral jsonb_each(w.value) a where a.value->>'personId'=any(person_ids) except select w.key,a.key,a.value from jsonb_each(coalesce(new.snapshot->'assignments','{}')) w cross join lateral jsonb_each(w.value) a where a.value->>'personId'=any(person_ids)) removed) into changed;
if changed then insert into ca_private.push_outbox(subscription_id,dedupe,title,body) values(s.id,'publication:'||new.cong_id||':'||new.version||':'||s.id,'Assignment update','Your published assignments changed. Open your workspace to check new, changed or cancelled assignments.') on conflict(dedupe) do nothing;end if;end loop;return new;end $$;
create trigger publication_push after insert or update on public.ca_oclm_publications for each row execute function ca_private.queue_publication_push();
create or replace function ca_private.queue_notice_push() returns trigger language plpgsql security definer set search_path='' as $$begin
if new.notes is distinct from old.notes and coalesce(new.notes,'') like '%[[CA_NOTICE]]%' then insert into ca_private.push_outbox(subscription_id,dedupe,title,body) select s.id,'notice:'||new.id||':'||md5(new.notes)||':'||s.id,'Congregation Assistant notice','A new announcement is available. Open your approved workspace to read it.' from ca_private.push_subscriptions s where s.cong_id=new.id on conflict(dedupe) do nothing;end if;return new;end $$;
create trigger announcement_push after update of notes on public.congregations for each row execute function ca_private.queue_notice_push();
create or replace function ca_private.push_rule(p_preferences jsonb,p_id text) returns jsonb language sql immutable set search_path='' as $$select r from jsonb_array_elements(coalesce(p_preferences->'rules','[]')) r where r->>'id'=p_id limit 1;$$;
create or replace function ca_private.push_rule_time(p_preferences jsonb,p_id text,p_default time) returns time language sql immutable set search_path='' as $$select coalesce((ca_private.push_rule(p_preferences,p_id)->>'time')::time,p_default);$$;
revoke all on function ca_private.push_rule(jsonb,text),ca_private.push_rule_time(jsonb,text,time) from public,anon,authenticated;
create or replace function public.claim_workspace_push() returns jsonb language plpgsql security definer set search_path='' as $$declare jobs jsonb;today date=(now() at time zone 'Asia/Kolkata')::date;begin
if auth.role() is distinct from 'service_role' then raise exception 'Worker access required' using errcode='42501';end if;
delete from ca_private.push_outbox where delivered_at<now()-interval '30 days' or attempts>=5 and next_attempt<now()-interval '7 days';
-- Recheck every recipient against current grants; revoked or expired access never receives queued work.
delete from ca_private.push_subscriptions s where not exists(select 1 from auth.users u where u.id=s.user_id and u.email_confirmed_at is not null) or not exists(select 1 from public.congregation_access a join public.congregations c on c.id=a.cong_id where a.cong_id=s.cong_id and a.email=s.email and a.active and(c.status='active' or c.status='trial' and c.created_at+c.trial_days*interval '1 day'>now()));
insert into ca_private.push_outbox(subscription_id,dedupe,title,body) select distinct s.id,'reports:'||date_trunc('month',local_time)::date||':'||s.id,'Service report reminder','Please check your report for last month in your approved workspace.' from ca_private.push_subscriptions s join public.congregation_access a on a.cong_id=s.cong_id and a.email=s.email and a.active and a.role in('admin','field_service','group_overseer','publisher') cross join lateral(select now() at time zone coalesce(s.preferences->>'timezone','Asia/Kolkata') local_time) clock where coalesce((s.preferences->>'reports')::boolean,true) and (local_time::date>date_trunc('month',local_time)::date or local_time::time>=ca_private.push_rule_time(s.preferences,'reports','09:00')) on conflict(dedupe) do nothing;
insert into ca_private.push_outbox(subscription_id,dedupe,title,body) select distinct s.id,'oclm:'||local_time::date||':'||s.id,'Schedule planning reminder','Please prepare and review OCLM assignments three weeks ahead.' from ca_private.push_subscriptions s join public.congregation_access a on a.cong_id=s.cong_id and a.email=s.email and a.active and a.role in('admin','oclm') cross join lateral(select now() at time zone coalesce(s.preferences->>'timezone','Asia/Kolkata') local_time) clock where coalesce((s.preferences->>'oclm')::boolean,true) and extract(dow from local_time)=coalesce((ca_private.push_rule(s.preferences,'oclm')->>'day')::integer,1) and local_time::time>=ca_private.push_rule_time(s.preferences,'oclm','09:00') on conflict(dedupe) do nothing;
insert into ca_private.push_outbox(subscription_id,dedupe,title,body) select distinct s.id,'attendance:'||(m->>'date')||':'||s.id,'Attendance reminder','Please check today’s meeting attendance and form link in your approved workspace.' from ca_private.push_subscriptions s join public.congregation_access a on a.cong_id=s.cong_id and a.email=s.email and a.active and a.role in('admin','attendance') cross join lateral(select ca_private.current_meeting(s.cong_id) m) meeting cross join lateral(select now() at time zone coalesce(s.preferences->>'timezone','Asia/Kolkata') local_time) clock where coalesce((s.preferences->>'attendance')::boolean,true) and (m->>'canSubmit')::boolean and coalesce((ca_private.push_rule(s.preferences,case when m->>'kind'='weekend' then 'attendance_weekend' else 'attendance_midweek' end)->>'enabled')::boolean,true) and local_time::time>=ca_private.push_rule_time(s.preferences,case when m->>'kind'='weekend' then 'attendance_weekend' else 'attendance_midweek' end,'21:00') on conflict(dedupe) do nothing;
insert into ca_private.push_outbox(subscription_id,dedupe,title,body) select distinct s.id,'attendance-link:'||(m->>'date')||':'||s.id,'Attendance form reminder','Please share the attendance form through your approved workspace.' from ca_private.push_subscriptions s join public.congregation_access a on a.cong_id=s.cong_id and a.email=s.email and a.active and a.role in('admin','attendance') cross join lateral(select ca_private.current_meeting(s.cong_id) m) meeting cross join lateral(select now() at time zone coalesce(s.preferences->>'timezone','Asia/Kolkata') local_time) clock where coalesce((ca_private.push_rule(s.preferences,'attendance_link')->>'enabled')::boolean,false) and (m->>'canSubmit')::boolean and extract(dow from local_time)=coalesce((ca_private.push_rule(s.preferences,'attendance_link')->>'day')::integer,3) and local_time::time>=ca_private.push_rule_time(s.preferences,'attendance_link','17:00') on conflict(dedupe) do nothing;
with selected as(select j.id from ca_private.push_outbox j where delivered_at is null and attempts<5 and next_attempt<=now() and(leased_at is null or leased_at<now()-interval '15 minutes') order by next_attempt limit 25 for update skip locked),leased as(update ca_private.push_outbox j set lease=gen_random_uuid(),leased_at=now(),attempts=attempts+1 from selected where j.id=selected.id returning j.*) select coalesce(jsonb_agg(jsonb_build_object('id',j.id,'lease',j.lease,'subscription',s.subscription,'title',j.title,'body',j.body)),'[]') into jobs from leased j join ca_private.push_subscriptions s on s.id=j.subscription_id;return jobs;end $$;
create or replace function public.finish_workspace_push(p_id uuid,p_lease uuid,p_status integer) returns boolean language plpgsql security definer set search_path='' as $$declare subscription uuid;begin if auth.role() is distinct from 'service_role' then raise exception 'Worker access required' using errcode='42501';end if;
update ca_private.push_outbox set delivered_at=case when p_status between 200 and 299 then now() else null end,next_attempt=now()+interval '30 minutes',leased_at=null,lease=null where id=p_id and lease=p_lease returning subscription_id into subscription;if subscription is null then return false;end if;if p_status in(404,410) then delete from ca_private.push_subscriptions where id=subscription;end if;return true;end $$;
revoke all on function public.register_push_subscription(text,jsonb,jsonb),public.remove_push_subscription(text),public.claim_workspace_push(),public.finish_workspace_push(uuid,uuid,integer),ca_private.queue_publication_push(),ca_private.queue_notice_push() from public,anon,authenticated;
grant execute on function public.register_push_subscription(text,jsonb,jsonb),public.remove_push_subscription(text) to authenticated;
grant execute on function public.claim_workspace_push(),public.finish_workspace_push(uuid,uuid,integer) to service_role;
