-- Shared private scheduling, optimistic concurrency and immutable publication versions.
create table if not exists public.ca_oclm_workspaces(cong_id text primary key references public.congregations(id) on delete cascade,revision bigint not null default 1 check(revision>0),data jsonb not null,updated_at timestamptz not null default now(),updated_by uuid);
create table if not exists public.ca_oclm_publication_history(cong_id text references public.congregations(id) on delete cascade,version bigint not null,snapshot jsonb not null,action text not null,week text,created_at timestamptz not null default now(),actor uuid,primary key(cong_id,version));
create table if not exists public.ca_oclm_assignment_events(id bigint generated always as identity primary key,cong_id text not null references public.congregations(id) on delete cascade,revision bigint not null,week text not null,slot text not null,assignment_type text,previous_person text,person_id text,status text not null,created_at timestamptz not null default now(),actor uuid);
create index if not exists oclm_events_cong_person_idx on public.ca_oclm_assignment_events(cong_id,person_id,created_at desc);
create index if not exists oclm_events_previous_person_idx on public.ca_oclm_assignment_events(cong_id,previous_person,created_at desc);
alter table public.ca_oclm_publications add column if not exists version bigint not null default 0;
update public.ca_oclm_publications set version=1 where version=0;
insert into public.ca_oclm_publication_history(cong_id,version,snapshot,action,created_at) select cong_id,version,snapshot,'initial_archive',updated_at from public.ca_oclm_publications on conflict do nothing;
do $$declare t text;begin foreach t in array array['ca_oclm_workspaces','ca_oclm_publication_history','ca_oclm_assignment_events'] loop execute format('alter table public.%I enable row level security',t);execute format('revoke all on public.%I from public,anon,authenticated',t);execute format('grant select on public.%I to authenticated',t);if not exists(select 1 from pg_policies where schemaname='public' and tablename=t and policyname='oclm_read') then execute format('create policy oclm_read on public.%I for select to authenticated using((select public.ca_has_role(cong_id,array[''oclm''])))',t);end if;end loop;end $$;
-- Direct writes and old whole-device publishing must not bypass version checks.
revoke insert,update,delete on public.ca_oclm_publications from authenticated;
revoke execute on function public.upsert_oclm_public_snapshot(text,jsonb) from public,anon,authenticated;
create or replace function ca_private.oclm_role_for_slot(p_slot text) returns text language sql immutable set search_path='' as $$select case when p_slot ~ '^Duty_[a-f0-9]{32}_[1-4]$' then regexp_replace(p_slot,'_[1-4]$','') when p_slot like '%Assistant%' then 'Assistant' else '{"Chairman":"Chairman","AuxiliaryCounselor":"Chairman","OpeningPrayer":"Prayer","ClosingPrayer":"Prayer","TreasuresTalk":"TreasuresTalk","SpiritualGems":"SpiritualGems","BibleReading":"BibleReading","BibleReadingAux":"BibleReading","Conversation":"Conversation","FollowingUp":"FollowingUp","Disciples":"Disciples","Beliefs":"Beliefs","ChristianPart1":"ChristianParts","ChristianPart2":"ChristianParts","ChristianPart3":"ChristianParts","BibleStudy":"BibleStudy","BibleStudyReader":"BibleStudyReader"}'::jsonb->>regexp_replace(p_slot,'Aux$','') end;$$;
create or replace function ca_private.safe_oclm_program(p_program jsonb) returns jsonb language plpgsql immutable set search_path='' as $$declare p jsonb;parts jsonb='[]';ids text[]='{}';begin
if jsonb_typeof(p_program) is distinct from 'object' or jsonb_typeof(p_program->'parts') is distinct from 'array' or jsonb_array_length(p_program->'parts')>36 then raise exception 'Invalid reviewed meeting program';end if;
for p in select value from jsonb_array_elements(p_program->'parts') loop
if coalesce(p->>'id','') !~ '^[A-Za-z][A-Za-z0-9_]{0,63}$' or p->>'id'=any(ids) or coalesce(p->>'type','')<>all(array['Chairman','Prayer','TreasuresTalk','SpiritualGems','BibleReading','Conversation','FollowingUp','Disciples','Beliefs','ChristianParts','BibleStudy','BibleStudyReader']) or coalesce(p->>'section','')<>all(array['treasures','field','living']) or coalesce(p->>'minutes','') !~ '^[0-9]{1,2}$' or (p->>'minutes')::integer>60 then raise exception 'Check each part ID, type, section and duration';end if;
ids=array_append(ids,p->>'id');parts=parts||jsonb_build_array(jsonb_build_object('id',p->>'id','type',p->>'type','section',p->>'section','title',left(coalesce(p->>'title',''),300),'minutes',(p->>'minutes')::integer,'assistant',coalesce((p->>'assistant')::boolean,false)));
end loop;return jsonb_build_object('parts',parts,'reviewed',coalesce((p_program->>'reviewed')::boolean,false),'reading',left(coalesce(p_program->>'reading',''),150),'sourceMonth',left(coalesce(p_program->>'sourceMonth',''),7));end $$;
create or replace function ca_private.clean_oclm_draft(p_cong text,p_data jsonb) returns jsonb language plpgsql stable security definer set search_path='' as $$declare person jsonb;pub public.publishers;people jsonb='[]';week record;part record;a jsonb;assignments jsonb='{}';week_data jsonb;programs jsonb='{}';program record;duty jsonb;duties jsonb='[]';period jsonb;away jsonb;exception_entry record;seen text[]='{}';begin
if jsonb_typeof(p_data) is distinct from 'object' or pg_column_size(p_data)>4194304 or jsonb_typeof(p_data->'personnel') is distinct from 'array' or jsonb_array_length(p_data->'personnel')>5000 or jsonb_typeof(p_data->'assignments') is distinct from 'object' or jsonb_typeof(p_data->'additionalDuties') is distinct from 'array' or jsonb_array_length(p_data->'additionalDuties')>20 or jsonb_typeof(coalesce(p_data->'programs','{}')) is distinct from 'object' then raise exception 'Invalid or oversized shared draft';end if;
for person in select value from jsonb_array_elements(p_data->'personnel') loop
if coalesce(person->>'id','') !~ '^[A-Za-z0-9_-]{1,100}$' or person->>'id'=any(seen) or length(trim(coalesce(person->>'name','')))=0 then raise exception 'Check the people in this draft';end if;seen=array_append(seen,person->>'id');
if nullif(person->>'publisherId','') is not null and (exists(select 1 from public.publishers where id=person->>'publisherId' and cong_id<>p_cong) or (not coalesce((person->>'archived')::boolean,false) and not exists(select 1 from public.publishers where id=person->>'publisherId' and cong_id=p_cong))) then raise exception 'Publisher is outside this congregation' using errcode='42501';end if;
if jsonb_typeof(coalesce(person->'roles','[]')) is distinct from 'array' or jsonb_typeof(coalesce(person->'exceptions','{}')) is distinct from 'object' or jsonb_typeof(coalesce(person->'availability','[]')) is distinct from 'array' or jsonb_array_length(coalesce(person->'availability','[]'))>50 then raise exception 'Check qualifications and away periods';end if;
away='[]';for exception_entry in select * from jsonb_each(coalesce(person->'exceptions','{}')) loop if exception_entry.key !~ '^[A-Za-z][A-Za-z0-9_]{0,100}$' or jsonb_typeof(exception_entry.value)<>'boolean' then raise exception 'Invalid qualification exception';end if;end loop;
for period in select value from jsonb_array_elements(coalesce(person->'availability','[]')) loop if coalesce(period->>'from','') !~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' or coalesce(period->>'to','') !~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' or (period->>'from')::date>(period->>'to')::date then raise exception 'Check each away period';end if;away=away||jsonb_build_array(jsonb_build_object('from',period->>'from','to',period->>'to'));end loop;
people=people||jsonb_build_array(jsonb_build_object('id',person->>'id','publisherId',person->>'publisherId','name',left(trim(person->>'name'),150),'gender',case when person->>'gender'='Female' then 'Female' else 'Male' end,'appointment',case when person->>'appointment'=any(array['Elder','MS','Sister']) then person->>'appointment' else 'Other' end,'roles',coalesce(person->'roles','[]'),'exceptions',coalesce(person->'exceptions','{}'),'availability',away,'archived',coalesce((person->>'archived')::boolean,false)));
end loop;
if (select count(*) from jsonb_object_keys(p_data->'assignments'))>520 then raise exception 'Too many meeting weeks';end if;
for week in select * from jsonb_each(p_data->'assignments') loop
if week.key !~ '^[0-9]{4}-W(0[1-9]|[1-4][0-9]|5[0-3])$' or jsonb_typeof(week.value) is distinct from 'object' or (select count(*) from jsonb_object_keys(week.value))>150 then raise exception 'Invalid meeting week';end if;week_data='{}';
for part in select * from jsonb_each(week.value) loop a=part.value;if part.key !~ '^[A-Za-z][A-Za-z0-9_]{0,100}$' or jsonb_typeof(a) is distinct from 'object' or coalesce(a->>'status','scheduled')<>all(array['scheduled','cancelled','reassigned','completed']) or nullif(a->>'personId','') is not null and not(a->>'personId'=any(seen)) then raise exception 'Check assignment identity and status';end if;
week_data=week_data||jsonb_build_object(part.key,jsonb_build_object('personId',a->>'personId','customTitle',left(coalesce(a->>'customTitle',''),300),'status',coalesce(a->>'status','scheduled'),'assignmentType',coalesce(a->>'assignmentType',ca_private.oclm_role_for_slot(part.key))));end loop;assignments=assignments||jsonb_build_object(week.key,week_data);end loop;
for program in select * from jsonb_each(coalesce(p_data->'programs','{}')) loop if program.key !~ '^[0-9]{4}-W(0[1-9]|[1-4][0-9]|5[0-3])$' then raise exception 'Invalid program week';end if;programs=programs||jsonb_build_object(program.key,ca_private.safe_oclm_program(program.value));end loop;
for duty in select value from jsonb_array_elements(p_data->'additionalDuties') loop if coalesce(duty->>'id','') !~ '^Duty_[a-f0-9]{32}$' or coalesce(duty->>'slots','') !~ '^[1-4]$' or length(trim(coalesce(duty->>'name','')))=0 then raise exception 'Check additional duties';end if;duties=duties||jsonb_build_array(jsonb_build_object('id',duty->>'id','name',left(trim(duty->>'name'),100),'section',left(coalesce(nullif(trim(duty->>'section'),''),'Additional Duties'),100),'slots',(duty->>'slots')::integer,'enabled',coalesce((duty->>'enabled')::boolean,true)));end loop;
return jsonb_build_object('v',3,'personnel',people,'assignments',assignments,'additionalDuties',duties,'programs',programs,'template',left(coalesce(p_data->>'template','modern'),40));end $$;
create or replace function public.get_oclm_workspace(p_cong_id text) returns jsonb language plpgsql stable security definer set search_path='' as $$declare w public.ca_oclm_workspaces;p public.ca_oclm_publications;begin if not public.ca_has_role(p_cong_id,array['oclm']) then raise exception 'Scheduler access required' using errcode='42501';end if;select * into w from public.ca_oclm_workspaces where cong_id=p_cong_id;select * into p from public.ca_oclm_publications where cong_id=p_cong_id;return jsonb_build_object('revision',coalesce(w.revision,0),'draft',w.data,'updatedAt',w.updated_at,'publication',case when p.cong_id is not null then jsonb_build_object('version',p.version,'token',p.token,'snapshot',p.snapshot,'publishedAt',p.updated_at) else null end);end $$;
create or replace function public.save_oclm_workspace(p_cong_id text,p_expected_revision bigint,p_data jsonb) returns jsonb language plpgsql security definer set search_path='' as $$declare old public.ca_oclm_workspaces;newrow public.ca_oclm_workspaces;clean jsonb;week text;slot text;before_part jsonb;after_part jsonb;begin
if not public.ca_has_role(p_cong_id,array['oclm']) then raise exception 'Scheduler access required' using errcode='42501';end if;
perform pg_advisory_xact_lock(hashtextextended('oclm:'||p_cong_id,0));select * into old from public.ca_oclm_workspaces where cong_id=p_cong_id;
if p_expected_revision is distinct from coalesce(old.revision,0) then raise exception 'This shared draft changed on another device. Keep your recovery copy and load the shared draft before editing.' using errcode='40001';end if;
clean=ca_private.clean_oclm_draft(p_cong_id,p_data);
insert into public.ca_oclm_workspaces(cong_id,revision,data,updated_at,updated_by) values(p_cong_id,coalesce(old.revision,0)+1,clean,clock_timestamp(),auth.uid()) on conflict(cong_id) do update set revision=excluded.revision,data=excluded.data,updated_at=excluded.updated_at,updated_by=excluded.updated_by returning * into newrow;
for week in select key from jsonb_each(coalesce(old.data->'assignments','{}')||(clean->'assignments')) loop
for slot in select key from jsonb_each(coalesce(old.data->'assignments'->week,'{}')||coalesce(clean->'assignments'->week,'{}')) loop
before_part=old.data->'assignments'->week->slot;after_part=clean->'assignments'->week->slot;
if (nullif(before_part->>'personId','') is not null or nullif(after_part->>'personId','') is not null) and (before_part->>'personId' is distinct from after_part->>'personId' or coalesce(before_part->>'status','scheduled') is distinct from coalesce(after_part->>'status','cancelled') or before_part->>'assignmentType' is distinct from after_part->>'assignmentType') then
insert into public.ca_oclm_assignment_events(cong_id,revision,week,slot,assignment_type,previous_person,person_id,status,actor) values(p_cong_id,newrow.revision,week,slot,coalesce(after_part->>'assignmentType',before_part->>'assignmentType',ca_private.oclm_role_for_slot(slot)),before_part->>'personId',after_part->>'personId',case when before_part->>'personId' is not null and after_part->>'personId' is not null and before_part->>'personId' is distinct from after_part->>'personId' then 'reassigned' else coalesce(after_part->>'status','cancelled') end,auth.uid());end if;end loop;end loop;
return jsonb_build_object('revision',newrow.revision,'draft',newrow.data,'updatedAt',newrow.updated_at);end $$;
create or replace function public.publish_oclm_week(p_cong_id text,p_week text,p_expected_revision bigint,p_expected_version bigint,p_remove boolean default false) returns jsonb language plpgsql security definer set search_path='' as $$declare w public.ca_oclm_workspaces;old public.ca_oclm_publications;p public.ca_oclm_publications;merged jsonb;assignments jsonb;week_data jsonb;people jsonb;layouts jsonb;metadata jsonb;old_week text;response jsonb;begin
if not public.ca_has_role(p_cong_id,array['oclm']) then raise exception 'Scheduler access required' using errcode='42501';end if;
if p_week !~ '^[0-9]{4}-W(0[1-9]|[1-4][0-9]|5[0-3])$' or p_remove is null then raise exception 'Choose a valid meeting week';end if;
perform pg_advisory_xact_lock(hashtextextended('oclm:'||p_cong_id,0));select * into w from public.ca_oclm_workspaces where cong_id=p_cong_id;select * into old from public.ca_oclm_publications where cong_id=p_cong_id;
if p_expected_version is distinct from coalesce(old.version,0) then raise exception 'The published schedule changed. Reload its latest version before publishing.' using errcode='40001';end if;
if w.cong_id is null or p_expected_revision is distinct from w.revision then raise exception 'The shared draft changed. Save and review its latest version before publishing.' using errcode='40001';end if;
assignments=coalesce(old.snapshot->'assignments','{}');layouts=coalesce(old.snapshot->'weekDetails','{}');
for old_week in select key from jsonb_each(assignments) loop if not layouts ? old_week then layouts=layouts||jsonb_build_object(old_week,jsonb_build_object('additionalDuties',coalesce(old.snapshot->'additionalDuties','[]'),'program',null));end if;end loop;
if p_remove then assignments=assignments-p_week;layouts=layouts-p_week;else
if not w.data->'assignments' ? p_week then raise exception 'No shared draft exists for this week';end if;
select coalesce(jsonb_object_agg(key,value),'{}') into week_data from jsonb_each(w.data->'assignments'->p_week) where coalesce(value->>'status','scheduled') not in('cancelled','reassigned');
assignments=assignments||jsonb_build_object(p_week,week_data);layouts=layouts||jsonb_build_object(p_week,jsonb_build_object('additionalDuties',w.data->'additionalDuties','program',w.data->'programs'->p_week));end if;
select coalesce(jsonb_agg(person),'[]') into people from(select distinct on (person->>'id') person from(select value person,1 precedence from jsonb_array_elements(coalesce(old.snapshot->'people','[]')) union all select value,0 from jsonb_array_elements(w.data->'personnel')) x order by person->>'id',precedence) chosen;
merged=jsonb_build_object('v',2,'kind','midweek','defaultWeek',p_week,'publishedWeeks',(select coalesce(jsonb_agg(key order by key),'[]') from jsonb_object_keys(assignments) key),'assignments',assignments,'people',people,'additionalDuties',w.data->'additionalDuties','generatedAt',extract(epoch from clock_timestamp())*1000);
perform set_config('ca.skip_publication_mail','true',true);response=public.upsert_oclm_public_snapshot(p_cong_id,merged);perform set_config('ca.skip_publication_mail','false',true);
update public.ca_oclm_publications set version=coalesce(old.version,0)+1,snapshot=snapshot||jsonb_build_object('weekDetails',layouts),updated_at=clock_timestamp() where cong_id=p_cong_id returning * into p;
insert into public.ca_oclm_publication_history(cong_id,version,snapshot,action,week,actor) values(p_cong_id,p.version,p.snapshot,case when p_remove then 'withdraw_week' else 'publish_week' end,p_week,auth.uid());
return jsonb_build_object('version',p.version,'token',p.token,'publishedAt',p.updated_at,'snapshot',p.snapshot);end $$;
create or replace function public.get_oclm_publication_history(p_cong_id text) returns jsonb language plpgsql stable security definer set search_path='' as $$begin if not public.ca_has_role(p_cong_id,array['oclm']) then raise exception 'Scheduler access required' using errcode='42501';end if;return(select coalesce(jsonb_agg(to_jsonb(h) order by version desc),'[]') from(select version,action,week,created_at from public.ca_oclm_publication_history where cong_id=p_cong_id order by version desc limit 100) h);end $$;
create or replace function public.rollback_oclm_publication(p_cong_id text,p_expected_version bigint,p_restore_version bigint) returns jsonb language plpgsql security definer set search_path='' as $$declare old public.ca_oclm_publications;target jsonb;p public.ca_oclm_publications;begin if not public.ca_has_role(p_cong_id,array['oclm']) then raise exception 'Scheduler access required' using errcode='42501';end if;
perform pg_advisory_xact_lock(hashtextextended('oclm:'||p_cong_id,0));select * into old from public.ca_oclm_publications where cong_id=p_cong_id;if old.cong_id is null or old.version is distinct from p_expected_version then raise exception 'The published version changed. Reload before restoring.' using errcode='40001';end if;select snapshot into target from public.ca_oclm_publication_history where cong_id=p_cong_id and version=p_restore_version;if target is null then raise exception 'Publication version not found';end if;
update public.ca_oclm_publications set snapshot=target,version=old.version+1,updated_at=clock_timestamp() where cong_id=p_cong_id returning * into p;insert into public.ca_oclm_publication_history(cong_id,version,snapshot,action,actor) values(p_cong_id,p.version,p.snapshot,'restore_version:'||p_restore_version,auth.uid());return jsonb_build_object('version',p.version,'token',p.token,'publishedAt',p.updated_at,'snapshot',p.snapshot);end $$;
revoke all on function ca_private.oclm_role_for_slot(text),ca_private.safe_oclm_program(jsonb),ca_private.clean_oclm_draft(text,jsonb) from public,anon,authenticated;
revoke all on function public.get_oclm_workspace(text),public.save_oclm_workspace(text,bigint,jsonb),public.publish_oclm_week(text,text,bigint,bigint,boolean),public.get_oclm_publication_history(text),public.rollback_oclm_publication(text,bigint,bigint) from public,anon,authenticated;
grant execute on function public.get_oclm_workspace(text),public.save_oclm_workspace(text,bigint,jsonb),public.publish_oclm_week(text,text,bigint,bigint,boolean),public.get_oclm_publication_history(text),public.rollback_oclm_publication(text,bigint,bigint) to authenticated;

create or replace function ca_private.notify_publication() returns trigger language plpgsql security definer set search_path='' as $$declare s ca_private.workspace_mail;begin if current_setting('ca.skip_publication_mail',true)='true' then return new;end if;select * into s from ca_private.workspace_mail where cong_id=new.cong_id and enabled and published;if s.cong_id is not null then insert into ca_private.mail_outbox(dedupe,email,subject,body) values('published:'||new.cong_id||':'||new.updated_at,s.email,'Meeting schedule published','A meeting schedule was published for your congregation. Open your approved workspace to review it. No publisher names or private records are included in this email.');end if;return new;end $$;
revoke all on function ca_private.notify_publication() from public,anon,authenticated;
