begin;
create table if not exists ca_private.workspace_applications(id uuid primary key default gen_random_uuid(),contact_name text not null,contact_email text not null,admin_email text not null,congregation_name text not null,phone text,created_at timestamptz not null default now(),status text not null default 'pending' check(status in('pending','approved','declined')),cong_id text references public.congregations(id),reviewed_by uuid);
create index if not exists workspace_application_queue_idx on ca_private.workspace_applications(status,created_at);
create index if not exists workspace_application_admin_idx on ca_private.workspace_applications(admin_email,created_at);
alter table ca_private.workspace_applications enable row level security;
revoke all on ca_private.workspace_applications from public,anon,authenticated;
create or replace function public.submit_workspace_application(p_name text,p_contact_email text,p_admin_email text,p_congregation text,p_phone text,p_authorized boolean,p_website text default '') returns jsonb language plpgsql security definer set search_path='' as $$declare result_id uuid;begin
if p_authorized is distinct from true or coalesce(p_website,'')<>'' then raise exception 'Confirm congregation authorization';end if;
if p_name is null or length(trim(p_name)) not between 2 and 100 or p_congregation is null or length(trim(p_congregation)) not between 2 and 150 or p_contact_email is null or length(p_contact_email)>150 or p_contact_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' or p_admin_email is null or lower(trim(p_admin_email)) !~ '^[a-z0-9._%+-]{1,64}@gmail\.com$' or length(coalesce(p_phone,''))>30 then raise exception 'Check your name, congregation, contact email and congregation Gmail';end if;
perform pg_advisory_xact_lock(hashtextextended('workspace-application-rate',0));
if(select count(*) from ca_private.workspace_applications where created_at>now()-interval '1 hour')>=20 or(select count(*) from ca_private.workspace_applications where status='pending')>=1000 then raise exception 'Requests are temporarily busy. Please retry later or contact support.';end if;
if exists(select 1 from ca_private.workspace_applications where admin_email=lower(trim(p_admin_email)) and status='pending') then return jsonb_build_object('received',true);end if;
insert into ca_private.workspace_applications(contact_name,contact_email,admin_email,congregation_name,phone) values(trim(p_name),lower(trim(p_contact_email)),lower(trim(p_admin_email)),trim(p_congregation),nullif(trim(p_phone),'')) returning id into result_id;
return jsonb_build_object('received',true,'reference',result_id);end $$;
create or replace function public.get_workspace_applications() returns jsonb language plpgsql stable security definer set search_path='' as $$begin if not public.ca_is_superadmin() then raise exception 'SuperAdmin access required' using errcode='42501';end if;return(select coalesce(jsonb_agg(to_jsonb(r)-'reviewed_by' order by created_at),'[]') from(select * from ca_private.workspace_applications order by created_at desc limit 200) r);end $$;
create or replace function public.review_workspace_application(p_id uuid,p_cong_id text,p_approve boolean) returns jsonb language plpgsql security definer set search_path='' as $$declare r ca_private.workspace_applications;letter text;begin
if not public.ca_is_superadmin() then raise exception 'SuperAdmin access required' using errcode='42501';end if;
select * into r from ca_private.workspace_applications where id=p_id for update;if r.id is null or r.status<>'pending' then raise exception 'This request has already been reviewed. Refresh the queue.';end if;
if p_approve is distinct from true then update ca_private.workspace_applications set status='declined',reviewed_by=auth.uid() where id=p_id;return jsonb_build_object('status','declined');end if;
if p_cong_id is null or p_cong_id !~ '^[A-Za-z0-9_-]{2,100}$' then raise exception 'Enter a congregation ID with letters, numbers, hyphens or underscores';end if;
-- Never overwrite an existing congregation or its administrator.
if exists(select 1 from public.congregations where id=p_cong_id) then raise exception 'That congregation ID is already in use. Choose another.';end if;
insert into public.congregations(id,name,email,status) values(p_cong_id,r.congregation_name,r.admin_email,'trial');
insert into public.congregation_access(cong_id,email,role,active) values(p_cong_id,r.admin_email,'admin',true);
update ca_private.workspace_applications set status='approved',cong_id=p_cong_id,reviewed_by=auth.uid() where id=p_id;
letter='Dear brothers,'||chr(10)||chr(10)||'Welcome to Congregation Assistant. Your workspace for '||r.congregation_name||' is ready.'||chr(10)||chr(10)||'Congregation ID: '||p_cong_id||chr(10)||'Administrator Google account: '||r.admin_email||chr(10)||'Open: https://photographicode.github.io/congregation-assistant/'||chr(10)||'Choose Continue with Google and use the approved congregation account. No password is sent by email.'||chr(10)||chr(10)||'After signing in, approve publisher accounts and assign department overseers in Settings. Publish the meeting schedule and share its notice-board link; each department can then publish duties to that same link. Each publisher can sign in with their approved Google account to see personal assignments and submit reports.'||chr(10)||chr(10)||'Guide: https://photographicode.github.io/Congregation-Assistant_Public/how-to-use.html'||chr(10)||'Your 30-day trial does not create an automatic charge.'||chr(10)||chr(10)||'Warm regards,'||chr(10)||'Congregation Assistant'||chr(10)||'Support: congregationassistant0@gmail.com';
insert into ca_private.mail_outbox(dedupe,email,subject,body) values('application-welcome-admin:'||r.id,r.admin_email,'Welcome to Congregation Assistant',letter) on conflict(dedupe) do nothing;
if r.contact_email<>r.admin_email then insert into ca_private.mail_outbox(dedupe,email,subject,body) values('application-welcome-contact:'||r.id,r.contact_email,'Your congregation workspace is ready','Dear '||r.contact_name||','||chr(10)||'Your request for '||r.congregation_name||' has been approved. Your congregation Gmail administrator can sign in with Google at https://photographicode.github.io/congregation-assistant/ . Ask that administrator to approve your publisher account. Help: congregationassistant0@gmail.com') on conflict(dedupe) do nothing;end if;
return jsonb_build_object('status','approved','congregationId',p_cong_id,'adminEmail',r.admin_email,'letter',letter,'emailStatus','queued');end $$;
create or replace function public.get_workspace_welcome(p_id uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$declare r ca_private.workspace_applications;letter text;begin
if not public.ca_is_superadmin() then raise exception 'SuperAdmin access required' using errcode='42501';end if;select * into r from ca_private.workspace_applications where id=p_id and status='approved';if r.id is null then raise exception 'Approved request not found';end if;
select body into letter from ca_private.mail_outbox where dedupe='application-welcome-admin:'||r.id;
return jsonb_build_object('letter',letter,'congregationId',r.cong_id,'adminEmail',r.admin_email,'emailStatus',(select state from ca_private.mail_outbox where dedupe='application-welcome-admin:'||r.id));end $$;
revoke all on function public.submit_workspace_application(text,text,text,text,text,boolean,text),public.get_workspace_applications(),public.review_workspace_application(uuid,text,boolean),public.get_workspace_welcome(uuid) from public,anon,authenticated;
grant execute on function public.submit_workspace_application(text,text,text,text,text,boolean,text) to anon,authenticated;
grant execute on function public.get_workspace_applications(),public.review_workspace_application(uuid,text,boolean),public.get_workspace_welcome(uuid) to authenticated;
create or replace function public.get_mail_delivery_health() returns jsonb language plpgsql stable security definer set search_path='' as $$begin if not public.ca_is_superadmin() then raise exception 'SuperAdmin access required' using errcode='42501';end if;return(select jsonb_build_object('queued',count(*) filter(where state in('queued','sending')),'failed',count(*) filter(where state='failed'),'sent',count(*) filter(where state='sent' and sent_at>now()-interval '7 days')) from ca_private.mail_outbox);end $$;
revoke all on function public.get_mail_delivery_health() from public,anon,authenticated;
grant execute on function public.get_mail_delivery_health() to authenticated;
commit;
