create or replace function public.export_congregation_workspace(p_cong_id text) returns jsonb language plpgsql stable security definer set search_path='' as $$declare payload jsonb;begin
if not public.ca_is_congregation_admin(p_cong_id) then raise exception 'Main administrator access required' using errcode='42501';end if;
payload=jsonb_build_object('format','ca-workspace-v1','congregation',p_cong_id,'profile',(select jsonb_build_object('name',name,'email',email,'notes',notes) from public.congregations where id=p_cong_id),'publishers',(select coalesce(jsonb_agg(to_jsonb(p) order by id),'[]') from public.publishers p where cong_id=p_cong_id),'reports',(select coalesce(jsonb_agg(to_jsonb(r) order by id),'[]') from public.reports r where cong_id=p_cong_id),'attendance',(select coalesce(jsonb_agg(to_jsonb(a) order by id),'[]') from public.meeting_attendance a where cong_id=p_cong_id),'meetingSettings',(select to_jsonb(s) from public.ca_meeting_settings s where cong_id=p_cong_id),'calendar',(select coalesce(jsonb_agg(to_jsonb(c) order by meeting_date),'[]') from public.ca_meeting_calendar c where cong_id=p_cong_id),'memorial',(select coalesce(jsonb_agg(to_jsonb(m) order by meeting_date),'[]') from public.ca_memorial_attendance m where cong_id=p_cong_id),'scheduler',(select data from public.ca_oclm_workspaces where cong_id=p_cong_id),'publication',(select snapshot from public.ca_oclm_publications where cong_id=p_cong_id),'publicationHistory',(select coalesce(jsonb_agg(to_jsonb(h)-'actor' order by version),'[]') from public.ca_oclm_publication_history h where cong_id=p_cong_id),'assignmentHistory',(select coalesce(jsonb_agg(to_jsonb(e)-'actor' order by id),'[]') from public.ca_oclm_assignment_events e where cong_id=p_cong_id),'access',(select coalesce(jsonb_agg(to_jsonb(a) order by id),'[]') from public.congregation_access a where cong_id=p_cong_id),'emailSettings',(select to_jsonb(s) from ca_private.workspace_mail s where cong_id=p_cong_id));
return jsonb_build_object('data',payload,'fingerprint',md5(payload::text));end $$;
create or replace function public.restore_congregation_workspace(p_cong_id text,p_expected_fingerprint text,p_backup jsonb) returns boolean language plpgsql security definer set search_path='' as $$declare current_backup jsonb;old_revision bigint;old_version bigint;restored jsonb;item jsonb;rowvalue jsonb;pub public.ca_oclm_publications;layouts jsonb='{}';meeting_week record;clean_layout jsonb;begin
if not public.ca_is_congregation_admin(p_cong_id) then raise exception 'Main administrator access required' using errcode='42501';end if;
perform pg_advisory_xact_lock(hashtextextended('oclm:'||p_cong_id,0));lock table public.publishers,public.reports,public.meeting_attendance,public.congregation_access,public.ca_meeting_settings,public.ca_meeting_calendar,public.ca_memorial_attendance in share row exclusive mode;
current_backup=public.export_congregation_workspace(p_cong_id);if p_expected_fingerprint is distinct from current_backup->>'fingerprint' then raise exception 'Workspace changed. Export its latest recovery copy before restoring.' using errcode='40001';end if;
if p_backup->>'format' is distinct from 'ca-workspace-v1' or p_backup->>'congregation' is distinct from p_cong_id or pg_column_size(p_backup)>33554432 then raise exception 'Choose a valid backup for this congregation';end if;
foreach rowvalue in array array[p_backup->'publishers',p_backup->'reports',p_backup->'attendance',p_backup->'calendar',p_backup->'memorial',p_backup->'access'] loop if jsonb_typeof(rowvalue) is distinct from 'array' then raise exception 'Backup datasets are incomplete';end if;end loop;
-- Preserve billing, public-link tokens and current membership grants. They are reviewed separately.
-- Publisher grants survive when their publisher IDs remain; omitted IDs remove those grants by FK.
set constraints all deferred;
delete from public.reports where cong_id=p_cong_id;delete from public.meeting_attendance where cong_id=p_cong_id;
-- Update existing publishers without deleting their bindings; insert absent records, remove omitted ones.
for item in select value from jsonb_array_elements(p_backup->'publishers') loop if item->>'cong_id' is distinct from p_cong_id then raise exception 'Foreign congregation record';end if;if exists(select 1 from public.publishers where id=item->>'id' and cong_id<>p_cong_id) then raise exception 'Foreign publisher ID' using errcode='42501';end if;
insert into public.publishers select (jsonb_populate_record(null::public.publishers,item)).* on conflict(id) do update set name=excluded.name,service_group=excluded.service_group,gender=excluded.gender,hope=excluded.hope,dob=excluded.dob,baptized=excluded.baptized,is_elder=excluded.is_elder,is_ms=excluded.is_ms,is_rp=excluded.is_rp,is_sp=excluded.is_sp,is_fm=excluded.is_fm,phone=excluded.phone,address=excluded.address,emergency_name=excluded.emergency_name,emergency_relationship=excluded.emergency_relationship,emergency_phone=excluded.emergency_phone,spiritual_status=excluded.spiritual_status,family_head_id=excluded.family_head_id;end loop;
delete from public.publishers where cong_id=p_cong_id and not exists(select 1 from jsonb_array_elements(p_backup->'publishers') p where p->>'id'=publishers.id);
for item in select value from jsonb_array_elements(p_backup->'reports') loop if item->>'cong_id' is distinct from p_cong_id then raise exception 'Foreign report';end if;insert into public.reports select (jsonb_populate_record(null::public.reports,item)).*;end loop;
for item in select value from jsonb_array_elements(p_backup->'attendance') loop if item->>'cong_id' is distinct from p_cong_id then raise exception 'Foreign attendance';end if;insert into public.meeting_attendance select (jsonb_populate_record(null::public.meeting_attendance,item)).*;end loop;
delete from public.ca_meeting_calendar where cong_id=p_cong_id;delete from public.ca_memorial_attendance where cong_id=p_cong_id;
for item in select value from jsonb_array_elements(p_backup->'calendar') loop if item->>'cong_id' is distinct from p_cong_id then raise exception 'Foreign meeting';end if;insert into public.ca_meeting_calendar select (jsonb_populate_record(null::public.ca_meeting_calendar,item)).*;end loop;
for item in select value from jsonb_array_elements(p_backup->'memorial') loop if item->>'cong_id' is distinct from p_cong_id then raise exception 'Foreign memorial record';end if;insert into public.ca_memorial_attendance(cong_id,meeting_date,attendance) values(p_cong_id,(item->>'meeting_date')::date,(item->>'attendance')::integer);end loop;
if jsonb_typeof(p_backup->'meetingSettings')='object' then item=p_backup->'meetingSettings';if item->>'cong_id' is distinct from p_cong_id or not exists(select 1 from pg_timezone_names where name=item->>'timezone') then raise exception 'Invalid meeting settings';end if;insert into public.ca_meeting_settings select (jsonb_populate_record(null::public.ca_meeting_settings,item)).* on conflict(cong_id) do update set timezone=excluded.timezone,midweek_day=excluded.midweek_day,weekend_day=excluded.weekend_day;else delete from public.ca_meeting_settings where cong_id=p_cong_id;end if;
select revision into old_revision from public.ca_oclm_workspaces where cong_id=p_cong_id;select version into old_version from public.ca_oclm_publications where cong_id=p_cong_id;
if jsonb_typeof(p_backup->'scheduler')='object' then restored=public.save_oclm_workspace(p_cong_id,coalesce(old_revision,0),p_backup->'scheduler');end if;
if jsonb_typeof(p_backup->'publication')='object' then perform set_config('ca.skip_publication_mail','true',true);perform public.upsert_oclm_public_snapshot(p_cong_id,p_backup->'publication');perform set_config('ca.skip_publication_mail','false',true);
for meeting_week in select * from jsonb_each(coalesce(p_backup->'publication'->'weekDetails','{}')) loop clean_layout=ca_private.clean_oclm_draft(p_cong_id,jsonb_build_object('personnel','[]'::jsonb,'assignments','{}'::jsonb,'additionalDuties',coalesce(meeting_week.value->'additionalDuties','[]'),'programs',case when jsonb_typeof(meeting_week.value->'program')='object' then jsonb_build_object(meeting_week.key,meeting_week.value->'program') else '{}'::jsonb end));layouts=layouts||jsonb_build_object(meeting_week.key,jsonb_build_object('additionalDuties',clean_layout->'additionalDuties','program',clean_layout->'programs'->meeting_week.key));end loop;
update public.ca_oclm_publications set snapshot=snapshot||jsonb_build_object('weekDetails',layouts),version=coalesce(old_version,0)+1,updated_at=clock_timestamp() where cong_id=p_cong_id returning * into pub;insert into public.ca_oclm_publication_history(cong_id,version,snapshot,action,actor) values(p_cong_id,pub.version,pub.snapshot,'restore_workspace',auth.uid());end if;
if jsonb_typeof(p_backup->'emailSettings')='object' then item=p_backup->'emailSettings';perform public.set_workspace_email(p_cong_id,item->>'email',(item->>'enabled')::boolean,(item->>'published')::boolean,(item->>'reports')::boolean,(item->>'oclm')::boolean,(item->>'oclm_day')::integer,(item->>'reminder_time')::time,item->>'timezone');perform public.set_attendance_email(p_cong_id,(item->>'attendance')::boolean,(item->>'attendance_link')::boolean,(item->>'attendance_time')::time,(item->>'attendance_link_time')::time);else delete from ca_private.workspace_mail where cong_id=p_cong_id;end if;
update public.congregations set name=left(p_backup->'profile'->>'name',150),email=left(p_backup->'profile'->>'email',254),notes=left(p_backup->'profile'->>'notes',10000) where id=p_cong_id;
return true;end $$;
revoke all on function public.export_congregation_workspace(text),public.restore_congregation_workspace(text,text,jsonb) from public,anon,authenticated;
grant execute on function public.export_congregation_workspace(text),public.restore_congregation_workspace(text,text,jsonb) to authenticated;
