/* Per-tab fictional sandbox. Every demo operation is intercepted before reaching the real backend. */
(()=>{'use strict';const KEY='ca_demo_session_v2';let state=null;
try{state=JSON.parse(sessionStorage.getItem(KEY)||'null');}catch{}
const clone=x=>JSON.parse(JSON.stringify(x)),active=()=>!!state&&sessionStorage.getItem('fs_cong_id')==='demo-cong'&&sessionStorage.getItem('fs_auth_type')==='demo';
function persist(){sessionStorage.setItem(KEY,JSON.stringify(state));}
const names=['Sample Arun','Sample Bala','Sample Chandra','Sample Deepak','Sample Elias','Sample Farah','Sample Grace','Sample Hari','Sample Isha','Sample Joel','Sample Kiran','Sample Leela'];
const departmentTitles={attendant:'Attendant (Attendance Department)',av:'Audio Video Department',cleaning:'Cleaning'};
function create(){const now=new Date(),year=now.getMonth()>=8?now.getFullYear()+1:now.getFullYear(),publishers=names.map((name,i)=>({id:'sample-pub-'+i,cong_id:'demo-cong',name,service_group:'Sample group '+(i%3+1),gender:i%3===2?'Female':'Male',is_elder:i===0||i===3,is_ms:i===1,is_rp:i===2||i===5,hope:'Other Sheep',phone:'',dob:null,baptized:null,address:'',emergency_name:'',emergency_phone:'',emergency_relationship:''})),reports=[];for(const sy of [year-1,year])for(let index=0;index<12;index++){const month=(index+8)%12,date=new Date(sy-(month>=8?1:0),month,1);if(date>=new Date(now.getFullYear(),now.getMonth(),1))continue;for(let i=0;i<publishers.length;i++)if(!(sy===year&&date.getMonth()===new Date(now.getFullYear(),now.getMonth()-1,1).getMonth()&&i===11))reports.push({id:publishers[i].id+'_'+sy+'_'+month,cong_id:'demo-cong',pub_id:publishers[i].id,service_year:sy,month,hours:publishers[i].is_rp?50:0,studies:i%3,shared_in_ministry:true,is_ap:false,comments:'Fictional sample report'});}
const duties=[['attendant','Attendant'],['av','Audio'],['av','Video'],['av','Microphones'],['cleaning','Cleaning']].map(([department,name],i)=>({id:'Duty_'+String(i+1).padStart(32,'0'),name,section:departmentTitles[department],slots:name==='Microphones'?2:1,enabled:true,department}));
return {tables:{congregations:[{id:'demo-cong',name:'Sample Congregation — fictional',status:'active',feature_attendance:true,feature_emergency_contacts:true,feature_oclm:true}],publishers,reports,meeting_attendance:[],congregation_access:[],group_access:[]},duties,people:Object.fromEntries(Object.keys(departmentTitles).map(dept=>[dept,publishers.slice(0,8).map(p=>({id:p.id,name:p.name,status:'approved',availability:[]}))])),revision:1,publications:{},tour:0};}
function query(table){const ops=[];const chain=new Proxy({}, {get(_,method){if(method==='then')return (resolve,reject)=>{try{if(!active())throw Error('Demo session ended.');let rows=state.tables[table]||[],filters=ops.filter(([name])=>['eq','in','neq'].includes(name)),matches=row=>filters.every(([name,key,value])=>name==='in'?value.includes(row[key]):name==='neq'?row[key]!==value:row[key]===value),write=ops.find(([name])=>['upsert','insert','update','delete'].includes(name));if(write){const [name,value]=write;if(name==='delete')state.tables[table]=rows.filter(row=>!matches(row));else if(name==='update')rows.filter(matches).forEach(row=>Object.assign(row,value));else for(const item of Array.isArray(value)?value:[value]){const row={...item,id:item.id||crypto.randomUUID()},index=rows.findIndex(r=>r.id===row.id);if(index<0)rows.push(row);else rows[index]=row;}state.tables[table]=state.tables[table]||rows;persist();}rows=(state.tables[table]||[]).filter(matches).map(clone);for(const [,key,option] of ops.filter(([name])=>name==='order'))rows.sort((a,b)=>String(a[key]).localeCompare(String(b[key]))*(option?.ascending===false?-1:1));const range=ops.find(([name])=>name==='range');if(range)rows=rows.slice(range[1],range[2]+1);resolve({data:ops.some(([name])=>name==='single'||name==='maybeSingle')?rows[0]||null:rows,error:null});}catch(e){reject(e);}};return (...args)=>{ops.push([method,...args]);return chain;};}});return chain;}
function scheduler(){const key=name=>'ca_midweek_demo-cong_'+name;let personnel=[],assignments={},duties=[];try{personnel=JSON.parse(sessionStorage.getItem(key('jw_scheduler_personnel'))||'[]');assignments=JSON.parse(sessionStorage.getItem(key('jw_scheduler_assignments'))||'{}');duties=JSON.parse(sessionStorage.getItem(key('jw_scheduler_additional_duties'))||'[]');}catch{}return {personnel,assignments,additionalDuties:duties};}
function storeScheduler(data){for(const [key,value] of Object.entries({jw_scheduler_personnel:data.personnel,jw_scheduler_assignments:data.assignments,jw_scheduler_additional_duties:data.additionalDuties}))sessionStorage.setItem('ca_midweek_demo-cong_'+key,JSON.stringify(value));}
function department(dept){const data=scheduler();return {publicationVersions:Object.fromEntries(Object.entries(state.publications||{}).filter(([key])=>key.startsWith(dept+'|')).map(([key,p])=>[key.split('|')[1],p.version])),publishedAt:Object.fromEntries(Object.entries(state.publications||{}).filter(([key])=>key.startsWith(dept+'|')).map(([key,p])=>[key.split('|')[1],p.date])),revision:state.revision,duties:data.additionalDuties.filter(d=>state.duties.some(r=>r.department===dept&&r.id===d.id)),people:state.tables.publishers.map(p=>({...state.people[dept].find(a=>a.id===p.id),id:p.id,name:p.name,status:dept==='cleaning'?'approved':state.people[dept].find(a=>a.id===p.id)?.status||'not_requested',availability:[]})),assignments:Object.fromEntries(Object.entries(data.assignments).map(([week,records])=>[week,Object.fromEntries(Object.entries(records).filter(([slot])=>state.duties.some(d=>d.department===dept&&slot.startsWith(d.id+'_'))).map(([slot,a])=>[slot,{...a,publisherId:a.personId,name:data.personnel.find(p=>p.id===a.personId)?.name}]))]))};}
async function rpc(name,args={}){try{if(!active())throw Error('Demo session ended.');if(args.p_cong_id&&args.p_cong_id!=='demo-cong')throw Error('Sample sessions cannot access another congregation.');let data;
if(name==='get_department_workspace')data=department(args.p_department);
else if(name==='get_managed_duties')data=state.duties.map(({id,department})=>({id,department}));
else if(name==='request_department_person'){const list=state.people[args.p_department],p=state.tables.publishers.find(p=>p.id===args.p_publisher_id);if(!p)throw Error('Choose a sample publisher.');const prior=list.find(p=>p.id===args.p_publisher_id);if(prior)prior.status=prior.status==='approved'?'approved':'pending';else list.push({id:p.id,name:p.name,status:'pending',availability:[]});data=true;}
else if(name==='decide_department_person'){const p=state.people[args.p_department].find(p=>p.id===args.p_publisher_id);if(!p)throw Error('Request this sample publisher first.');p.status=args.p_approve?'approved':'rejected';data=true;}
else if(name==='save_department_duty'){if(args.p_expected_revision!==state.revision)throw Object.assign(Error('Schedule changed. Reload first.'),{code:'40001'});const draft=scheduler(),id=args.p_id||'Duty_'+crypto.randomUUID().replace(/-/g,''),d={id,name:args.p_name,slots:args.p_slots,section:departmentTitles[args.p_department],enabled:args.p_enabled};draft.additionalDuties=draft.additionalDuties.filter(d=>d.id!==id).concat(d);if(!state.duties.some(r=>r.id===id))state.duties.push({...d,department:args.p_department});storeScheduler(draft);state.revision++;data=department(args.p_department);}
else if(name==='save_department_assignments'){if(args.p_expected_revision!==state.revision)throw Object.assign(Error('Schedule changed. Reload first.'),{code:'40001'});const draft=scheduler(),week=draft.assignments[args.p_week]||{};for(const [slot,pid] of Object.entries(args.p_assignments)){if(pid&&!state.people[args.p_department].some(p=>p.id===pid&&p.status==='approved')&&args.p_department!=='cleaning')throw Error('Administrator approval required.');week[slot]={personId:pid||null,status:'scheduled',customTitle:'',assignmentType:slot.replace(/_[1-4]$/,'')};}draft.assignments[args.p_week]=week;storeScheduler(draft);state.revision++;data=department(args.p_department);}
else if(name==='publish_department_week'){state.publications=state.publications||{};const key=args.p_department+'|'+args.p_week,old=state.publications[key];if(args.p_expected_revision!==state.revision||args.p_expected_version!==(old?.version||0))throw Object.assign(Error('Schedule changed. Reload first.'),{code:'40001'});state.publications[key]={version:(old?.version||0)+1,date:new Date().toISOString(),data:department(args.p_department)};data=department(args.p_department);data.publicationVersions=Object.fromEntries(Object.entries(state.publications).filter(([key])=>key.startsWith(args.p_department+'|')).map(([key,p])=>[key.split('|')[1],p.version]));data.publishedAt=Object.fromEntries(Object.entries(state.publications).filter(([key])=>key.startsWith(args.p_department+'|')).map(([key,p])=>[key.split('|')[1],p.date]));}
else if(name==='get_oclm_roster')data=state.tables.publishers.map(p=>({id:p.id,name:p.name,gender:p.gender,isElder:p.is_elder,isMS:p.is_ms}));
else if(name==='get_attendance_calendar')data={settings:{timezone:'Asia/Kolkata',midweek_day:3,weekend_day:0},events:[],memorials:[]};
else if(['save_meeting_calendar','save_memorial_attendance'].includes(name))data=true;
else if(name==='ca_is_superadmin')data=false;
else throw Error('This action needs a real approved workspace. The sample congregation creates no public links, emails or push notifications.');
persist();if(['save_department_assignments','save_department_duty'].includes(name))window.reloadSchedulerDemo?.();return {data,error:null};}catch(e){return {data:null,error:{message:e.message,code:e.code}};}}
function seedScheduler(){const people=state.tables.publishers.map(p=>({id:p.id,publisherId:p.id,name:p.name,gender:p.gender,appointment:p.is_elder?'Elder':p.is_ms?'MS':p.gender==='Female'?'Sister':'Other',roles:['Prayer','BibleReading','Assistant','Conversation','FollowingUp','Disciples','Beliefs','ChristianParts',...state.duties.map(d=>d.id)],exceptions:{},availability:[],archived:false})),week=window.CADepartments.weekId(),assignments={[week]:{Chairman:{personId:people[0].id,status:'scheduled'},OpeningPrayer:{personId:people[1].id,status:'scheduled'},BibleReading:{personId:people[3].id,status:'scheduled'}}};state.duties.forEach((d,i)=>{for(let slot=1;slot<=d.slots;slot++)assignments[week][d.id+'_'+slot]={personId:people[(i+slot)%8].id,status:'scheduled',customTitle:'',assignmentType:d.id};});storeScheduler({personnel:people,assignments,additionalDuties:state.duties.map(({department,...d})=>d)});}
async function resume(){window.currentCongId='demo-cong';window.auth.roleReady=false;window.auth.verifiedRoles=[];window.auth.verifiedOwner=false;window.db.currentCongData=state.tables.congregations[0];document.getElementById('auth-screen').classList.add('hidden');await window.db.initAdmin('demo-cong',state.tables.congregations[0].name);window.ui.applyRoleNavigation();window.ui.switchTab('dashboard');document.getElementById('global-loader').classList.add('hidden');let banner=document.getElementById('demo-session-banner');if(!banner){banner=document.createElement('aside');banner.id='demo-session-banner';banner.className='ca-demo-banner';document.querySelector('main')?.prepend(banner);}banner.innerHTML='<strong>Sample congregation — fictional records</strong><span>Changes stay in this demo. Each new entry starts fresh.</span><button type="button" data-tour>Show tour</button><button type="button" data-exit>Leave demo</button>';banner.querySelector('[data-tour]').onclick=()=>tour(0);banner.querySelector('[data-exit]').onclick=()=>window.auth.endSession();if(state.tour===0)tour(0);}
async function start(){if(window.currentCongId&&window.currentCongId!=='demo-cong'){window.ui.showToast('Sign out of your real workspace before trying the sample.','error');return;}state=create();for(const key of Object.keys(sessionStorage))if(key.startsWith('ca_midweek_demo-cong_'))sessionStorage.removeItem(key);for(const [key,value] of Object.entries({fs_auth:'true',fs_auth_type:'demo',fs_role:'admin',fs_roles:'["admin"]',fs_cong_id:'demo-cong',fs_cong_name:'Sample Congregation — fictional',fs_last_activity:String(Date.now())}))sessionStorage.setItem(key,value);sessionStorage.removeItem('ca_signed_out');seedScheduler();window.reloadSchedulerDemo?.();persist();window.CADepartments.clear();await resume();}
const tourSteps=[['dashboard','Welcome to the sample congregation','These records are fictional. Try each tool without changing anyone’s real information.'],['groups','Field service groups','Three sample groups are filled. Open a group to see publishers and missing reports.'],['analytics','Reports across two service years','Sample reports cover the previous service year and completed months of this year. Choose a year to compare.'],['duties','Departments work together','Attendant and Audio Video have their own duties. AV and Attendant publishers need administrator approval. Cleaning does not. Each department assigns and publishes its own week.'],['oclm','One schedule to review and publish','Choose week → assign people → review → publish. The demo simulates publication; a real workspace creates the live link.']];
function tour(index){document.getElementById('demo-tour')?.remove();if(index>=tourSteps.length){state.tour=1;persist();return;}const [tab,title,body]=tourSteps[index];window.ui.switchTab(tab);const box=document.createElement('div');box.id='demo-tour';box.className='ca-demo-tour';box.setAttribute('role','dialog');box.setAttribute('aria-modal','true');box.setAttribute('aria-labelledby','demo-tour-title');box.innerHTML=`<div><p>Step ${index+1} of ${tourSteps.length}</p><h2 id="demo-tour-title">${title}</h2><p>${body}</p><button type="button" data-next>${index===tourSteps.length-1?'Start exploring':'Next'}</button><button type="button" data-skip>Skip tour</button></div>`;document.body.append(box);box.querySelector('[data-next]').onclick=()=>{window.AppSupport?.dialogClosed(box);tour(index+1);};box.querySelector('[data-skip]').onclick=()=>{window.AppSupport?.dialogClosed(box);box.remove();state.tour=1;persist();};window.AppSupport?.dialogOpened(box);box.querySelector('[data-next]').focus();}
function leave(){state=null;sessionStorage.removeItem(KEY);document.getElementById('demo-session-banner')?.remove();document.getElementById('demo-tour')?.remove();}
window.CADemo={get active(){return active();},start,resume,leave,wrap(real){return new Proxy(real,{get(target,key){if(key==='from')return (...args)=>active()?query(...args):target.from(...args);if(key==='rpc')return (...args)=>active()?rpc(...args):target.rpc(...args);if(key==='auth')return new Proxy(target.auth,{get(a,k){if(k==='getSession'&&active())return async()=>({data:{session:null},error:null});const v=a[k];return typeof v==='function'?v.bind(a):v;}});const v=target[key];return typeof v==='function'?v.bind(target):v;}});}};
})();
