/* Browser acceptance fixture. Never connects to a real database. */
(() => {
    if(window.top!==window)return;
    const cong = { id: 'qa-congregation', name: window.__CA_DEMO_CAPTURE ? 'Demo Congregation' : 'Acceptance Test', status: 'active', feature_attendance: true, feature_emergency_contacts: true, feature_oclm: true };
    const publishers = Array.from({ length: 1000 }, (_, i) => ({ id: `qa-${i}`, cong_id: cong.id, name: i === 0 ? 'Alex O\'Brien & Family' : `Publisher ${String(i).padStart(4, '0')}`, service_group: `Group ${i % 10}`, gender: i % 2 ? 'Female' : 'Male', hope: 'Other Sheep', dob: '1990-01-01', baptized: '2010-01-01', is_elder: i % 30 === 0, is_ms: false, is_rp: i % 20 === 0, is_sp: false, is_fm: false, phone: '1234567890', address: '17 Example Street', emergency_name: 'Emergency Contact', emergency_relationship: 'Family', emergency_phone: '1234567890' }));
    const tables = { congregations: [cong], publishers, reports: [], meeting_attendance: [], congregation_access: [{cong_id:cong.id,email:'qa-admin@example.com',role:'admin',active:true}], group_access: [] };
    const backend = window.__qaBackend = { tables, writes: [], rejectWrites: false, delay: 0, session: sessionStorage.getItem('ca_signed_out')==='true'?null:{user:{email:'qa-admin@example.com',app_metadata:{provider:'google'}}}, drafts:{}, publicationVersions:{}, oauthRequests: [], rpcCalls: [], publications: {}, publicLinks: {}, reads: [] };

    backend.departmentDrafts={};backend.departmentDefs=[];backend.departmentPeople={};backend.departmentPublications={};backend.applications=[];
    function departmentDraft(cong,dept){return backend.departmentDrafts[cong+'|'+dept]||{revision:0,draft:{v:3,personnel:[],assignments:{},additionalDuties:[],programs:{},template:'modern'}};}
    function departmentWorkspace(cong,dept){const w=departmentDraft(cong,dept),data=w.draft,defs=backend.departmentDefs.filter(d=>d.cong===cong&&d.department===dept);return {publicationVersions:Object.fromEntries(Object.entries(backend.departmentPublications).filter(([key])=>key.startsWith(cong+'|'+dept+'|')).map(([key,p])=>[key.split('|')[2],p.version])),publishedAt:Object.fromEntries(Object.entries(backend.departmentPublications).filter(([key])=>key.startsWith(cong+'|'+dept+'|')).map(([key,p])=>[key.split('|')[2],p.date])),token:backend.publications[cong]?.token,revision:w.revision,duties:data.additionalDuties.filter(d=>defs.some(r=>r.id===d.id)),people:tables.publishers.filter(p=>p.cong_id===cong).map(p=>({id:p.id,name:p.name,status:backend.departmentPeople[cong+'|'+dept+'|'+p.id]||'not_requested',availability:data.personnel.find(r=>r.publisherId===p.id||r.id===p.id)?.availability||[]})),assignments:Object.fromEntries(Object.entries(data.assignments).map(([week,records])=>[week,Object.fromEntries(Object.entries(records).filter(([slot])=>defs.some(d=>slot.startsWith(d.id+'_'))).map(([slot,a])=>{const person=data.personnel.find(p=>p.id===a.personId);return [slot,{...a,name:person?.name,publisherId:person?.publisherId||person?.id}];}))]))};}
    function departmentRpc(name,args){const cong=args.p_cong_id,dept=args.p_department,w=departmentDraft(cong,dept);if(name==='get_managed_duties')return {data:backend.departmentDefs.filter(d=>d.cong===cong).map(({id,department})=>({id,department})),error:null};if(name==='get_department_workspace')return {data:departmentWorkspace(cong,dept),error:null};if(backend.rejectWrites)return {error:{message:'Acceptance test: save rejected'}};if(name==='request_department_person'){backend.departmentPeople[cong+'|'+dept+'|'+args.p_publisher_id]='pending';return {data:true,error:null};}if(name==='decide_department_person'){backend.departmentPeople[cong+'|'+dept+'|'+args.p_publisher_id]=args.p_approve?'approved':'rejected';return {data:true,error:null};}if(name==='publish_department_week'){backend.publications[cong]||={token:'qa-notice-token'};const key=cong+'|'+dept+'|'+args.p_week,old=backend.departmentPublications[key];if(args.p_expected_revision!==w.revision||args.p_expected_version!==(old?.version||0))return {error:{code:'40001',message:'Publication changed'}};backend.departmentPublications[key]={version:(old?.version||0)+1,date:new Date().toISOString(),snapshot:JSON.parse(JSON.stringify(departmentWorkspace(cong,dept)))};return {data:departmentWorkspace(cong,dept),error:null};}
    if(args.p_expected_revision!==w.revision)return {error:{code:'40001',message:'Shared draft changed'}};const draft=JSON.parse(JSON.stringify(w.draft));if(name==='save_department_duty'){const id=args.p_id||'Duty_'+crypto.randomUUID().replace(/-/g,''),duty={id,name:args.p_name,slots:args.p_slots,enabled:args.p_enabled,section:{av:'Audio Video Department',attendant:'Attendant (Attendance Department)',cleaning:'Cleaning'}[dept]};draft.additionalDuties=draft.additionalDuties.filter(d=>d.id!==id).concat(duty);if(!backend.departmentDefs.some(d=>d.id===id))backend.departmentDefs.push({cong,id,department:dept});}else if(name==='save_department_assignments'){const week=draft.assignments[args.p_week]||{};for(const [slot,pid] of Object.entries(args.p_assignments)){if(pid&&backend.departmentPeople[cong+'|'+dept+'|'+pid]!=='approved')return {error:{message:'Administrator approval required'}};let person=draft.personnel.find(p=>p.publisherId===pid||p.id===pid);if(pid&&!person){const pub=tables.publishers.find(p=>p.id===pid&&p.cong_id===cong);person={id:pid,publisherId:pid,name:pub.name,roles:[],exceptions:{},availability:[],gender:pub.gender,appointment:'Other'};draft.personnel.push(person);}week[slot]={personId:person?.id||null,status:'scheduled',customTitle:'',assignmentType:slot.replace(/_[1-4]$/,'')};}draft.assignments[args.p_week]=week;}
    backend.departmentDrafts[cong+'|'+dept]={revision:w.revision+1,draft};return {data:departmentWorkspace(cong,dept),error:null};}
    window.supabase = { createClient: () => ({
        auth: { getSession: async () => ({ data: { session: backend.session } }), signInWithOAuth: async options => { backend.oauthRequests.push(options); return { error: null }; }, setSession: async () => {backend.session={user:{email:"owner@example.com"}};return {data:{session:backend.session},error:null};}, signInWithPassword: async ({email,password}) => {if(password!=="qa-owner-password")return {data:{session:null},error:{message:"Invalid login credentials"}};backend.session={user:{email}};return {data:{session:backend.session},error:null};}, signOut: async () => {backend.session=null;return {error:null};} },
        from(table) {
            const operations = [];backend.reads.push(table);
            const chain = new Proxy({}, { get: (_, method) => method === 'then' ? (resolve, reject) => {
                const execute = async () => {
                    const write = operations.find(([name]) => ['upsert', 'insert', 'update', 'delete'].includes(name));
                    if (backend.delay) await new Promise(done => setTimeout(done, backend.delay));
                    if (write) {
                        backend.writes.push({ table, operations });
                        if (backend.rejectWrites) return { data: null, error: { message: 'Acceptance test: save rejected' } };
                        const [name, payload] = write;
                        if (name === 'upsert' || name === 'insert') for (const row of Array.isArray(payload) ? payload : [payload]) {
                            const list = tables[table] ||= [], index = list.findIndex(item => item.id === row.id);
                            if (index < 0) list.push({ ...row }); else list[index] = { ...list[index], ...row };
                        }
                    }
                    let data = (tables[table] || []).filter(row => operations.filter(([name]) => name === 'eq').every(([, field, value]) => row[field] === value)&&operations.filter(([name])=>name==='in').every(([,field,values])=>values.includes(row[field])));
                    const order=operations.find(([name])=>name==='order');if(order)data.sort((a,b)=>String(a[order[1]]).localeCompare(String(b[order[1]])));const range=operations.find(([name])=>name==='range');if(range)data=data.slice(range[1],range[2]+1);
                    if (operations.some(([name]) => name === 'single' || name === 'maybeSingle')) data = data[0] || null;
                    return { data, error: null };
                };
                execute().then(resolve, reject);
            } : (...args) => { operations.push([method, ...args]); return chain; } });
            return chain;
        }, rpc: async (name,args) => {
            backend.rpcCalls.push({name,args});if(name==='submit_family_report'&&backend.familyDelay)await new Promise(resolve=>setTimeout(resolve,backend.familyDelay));
            if(name==='get_workspace_applications')return {data:backend.applications,error:null};
            if(name==='get_trial_requests')return {data:[],error:null};
            if(name==='review_workspace_application'){const r=backend.applications.find(r=>r.id===args.p_id);r.status=args.p_approve?'approved':'declined';r.cong_id=args.p_cong_id;if(args.p_approve)tables.congregations.push({id:args.p_cong_id,name:r.congregation_name,status:'trial'});return {data:{status:r.status,congregationId:r.cong_id,letter:'Dear brothers,\nWelcome to your fictional workspace.\nAdministrator: fictional-congregation@gmail.com\nContinue with Google. No password is sent by email.\nWarm regards,\nCongregation Assistant',emailStatus:'queued'},error:null};}
            if(name==='get_workspace_welcome')return {data:{letter:'Dear brothers,\nWelcome to your fictional workspace.\nAdministrator: fictional-congregation@gmail.com\nContinue with Google. No password is sent by email.\nWarm regards,\nCongregation Assistant',emailStatus:'queued'},error:null};

            if(name==='get_publisher_transfer'){const p=tables.publishers.find(p=>p.id===args.p_publisher_id);return {data:{publisher:Object.fromEntries(Object.entries(p).filter(([key])=>!['cong_id','service_group','family_head_id'].includes(key))),congregation:'Sample congregation',reports:tables.reports.filter(r=>r.pub_id===p.id)},error:null};}
            if(name==='transfer_publisher'){const p=tables.publishers.find(p=>p.id===args.p_publisher_id);p.transferred_at=new Date().toISOString();p.service_group=null;return {data:true,error:null};}

            if(['get_managed_duties','get_department_workspace','request_department_person','decide_department_person','save_department_duty','save_department_assignments','publish_department_week'].includes(name))return departmentRpc(name,args);
            if(name==='get_publisher_login'){backend.loginEmails ||= {};return {data:backend.loginEmails[args.p_publisher_id]||[],error:null};}
            if(name==='set_publisher_login'){if(backend.rejectWrites||backend.rejectLoginWrites)return {error:{message:'Acceptance test: login save rejected'}};backend.loginEmails ||= {};backend.loginEmails[args.p_publisher_id]=args.p_email?[args.p_email]:[];return {data:backend.loginEmails[args.p_publisher_id],error:null};}
            if(name==='save_congregation_reports'){if(backend.rejectWrites)return {data:null,error:{message:'Acceptance test: save rejected'}};const saved=args.p_reports.map(r=>{const existing=tables.reports.find(x=>x.pub_id===r.pub_id&&x.service_year===r.service_year&&x.month===r.month);const row=r.clear_auxiliary&&existing?{...existing,is_ap:false,hours:0,comments:''}:{...r,id:existing?.id||crypto.randomUUID()};delete row.clear_auxiliary;if(existing)Object.assign(existing,row);else tables.reports.push(row);return row;});backend.writes.push({table:'reports',method:'rpc',payload:saved});return {data:saved,error:null};}
            if(name==='get_attendance_meeting')return {data:backend.meetingContext||{configured:true,date:'2026-10-05',kind:'midweek',serviceYear:2027,month:9,week:1,timezone:'Asia/Kolkata',canSubmit:true,count:82},error:null};
            if(name==='submit_current_attendance')return backend.rejectWrites?{data:null,error:{message:'Acceptance test: save rejected'}}:{data:true,error:null};
            if(name==='get_attendance_calendar')return {data:{settings:{timezone:'Asia/Kolkata',midweek_day:3,weekend_day:0},events:[],memorials:[{meeting_date:'2026-04-02',service_year:2026,attendance:149}]},error:null};
            if(name==='request_congregation_trial')return backend.rejectWrites?{data:null,error:{message:'Acceptance test: request rejected'}}:{data:{reference:'339f299d-a5db-4b6e-9d87-067dabfd67ad',status:'pending',emailQueued:true},error:null};
            if(name==='get_trial_requests')return {data:[],error:null};
            if(name==='review_workspace_application'){const r=backend.applications.find(r=>r.id===args.p_id);r.status=args.p_approve?'approved':'declined';r.cong_id=args.p_cong_id;if(args.p_approve)tables.congregations.push({id:args.p_cong_id,name:r.congregation_name,status:'trial'});return {data:{status:r.status,congregationId:r.cong_id,letter:'Dear brothers,\nWelcome to your fictional workspace.\nAdministrator: fictional-congregation@gmail.com\nContinue with Google. No password is sent by email.\nWarm regards,\nCongregation Assistant',emailStatus:'queued'},error:null};}
            if(name==='get_workspace_welcome')return {data:{letter:'Dear brothers,\nWelcome to your fictional workspace.\nAdministrator: fictional-congregation@gmail.com\nContinue with Google. No password is sent by email.\nWarm regards,\nCongregation Assistant',emailStatus:'queued'},error:null};

            if(name==='save_group_reports'){
                if(backend.rejectWrites)return {data:null,error:{message:'Acceptance test: save rejected'}};
                const saved=args.p_reports.map((r,i)=>({...r,id:'group-report-'+i,cong_id:args.p_cong_id,service_year:args.p_year,month:args.p_month}));
                tables.reports.push(...saved);backend.writes.push({table:'reports',method:'rpc',payload:saved});return {data:saved,error:null};
            }
            if(name==='get_admin_home_tasks')return {data:{publisherCount:tables.publishers.filter(p=>p.cong_id===args.p_cong_id&&!p.transferred_at).length,missingScheduleWeeks:['2026-W43'],requests:Object.entries(backend.departmentPeople).filter(([key])=>key.startsWith(args.p_cong_id+'|')).map(([key,status])=>({department:key.split('|')[1],publisherId:key.split('|')[2],name:tables.publishers.find(p=>p.id===key.split('|')[2])?.name,status,updatedAt:new Date().toISOString()}))},error:null};
            if(name==='get_my_publisher_portal'){backend.personal ||= {publisherId:'qa-0',reportPublishers:[{id:'qa-0',name:'Personal Sample Publisher'}],name:'Personal Sample Publisher',email:'qa@example.com',profileComplete:true,assignments:[{week:'2026-W42',date:'2026-10-14',slot:'BibleReading',title:'My sample assignment'}],report:{period:'September 2026',submitted:false,hoursRequired:false,record:null},notice:null,contact:{phone:'0000000000',address:'Fictional address',emergency_name:'Sample Relative',emergency_relationship:'Relative',emergency_phone:'0000000001'},away:[],reminders:[],scheduleRevision:0,preferencesRevision:0,timezone:'Asia/Kolkata',schedule:{publishedWeeks:['2026-W42'],people:[{id:'qa-0',name:'Sample Publisher'}],assignments:{'2026-W42':{BibleReading:{personId:'qa-0'}}}},attendance:null};return {data:structuredClone(backend.personal),error:null};}
            if(['update_my_publisher_contact','save_my_publisher_away','save_my_publisher_reminders','submit_my_attendance'].includes(name)){if(backend.rejectWrites)return {error:{message:'Acceptance test: save rejected'}};const h=backend.personal;if(name==='update_my_publisher_contact'){h.contact=args.p_contact;return {data:h.contact,error:null};}if(name==='save_my_publisher_away'){h.away=args.p_away;h.scheduleRevision++;return {data:{away:h.away,scheduleRevision:h.scheduleRevision},error:null};}if(name==='save_my_publisher_reminders'){h.reminders=args.p_reminders;h.preferencesRevision++;return {data:{reminders:h.reminders,preferencesRevision:h.preferencesRevision},error:null};}h.attendance.count=args.p_count;return {data:true,error:null};}
            if(name==='get_my_publisher_home')return {data:{publisherId:'qa-0',reportPublishers:[{id:'qa-0',name:'Personal Sample Publisher'}],name:'Personal Sample Publisher',email:'qa@example.com',profileComplete:true,assignments:[{week:'2026-W42',slot:'BibleReading',title:'My sample assignment'}],report:{period:'September 2026',submitted:false,hoursRequired:false,record:null},notice:null},error:null};
            if(name==='get_my_family_report'){const id=args.p_publisher_id;if(!backend.personal.reportPublishers.some(p=>p.id===id))return {error:{message:'Report permission denied'}};return {data:structuredClone(id===backend.personal.publisherId?{publisherId:id,name:backend.personal.name,report:backend.personal.report}:backend.familyReports[id]),error:null};}
            if(name==='submit_family_report'){if(backend.rejectWrites)return {error:{message:'Acceptance test: report save rejected'}};const id=args.p_publisher_id;if(!backend.personal.reportPublishers.some(p=>p.id===id))return {error:{message:'Report permission denied'}};const target=id===backend.personal.publisherId?backend.personal:backend.familyReports[id];target.report.submitted=true;target.report.record={shared:args.p_shared,studies:args.p_studies,hours:args.p_hours,comments:args.p_comments,auxiliaryPioneer:args.p_hours>0&&!target.report.hoursRequired};return {data:structuredClone({publisherId:id,name:target.name,report:target.report,saved:true}),error:null};}
            if(name==='submit_my_publisher_report'){if(backend.rejectWrites)return {error:{message:'Acceptance test: report save rejected'}};backend.personal.report.submitted=true;backend.personal.report.record={shared:args.p_shared,studies:args.p_studies,hours:args.p_hours,comments:args.p_comments,auxiliaryPioneer:args.p_auxiliary};return {data:{saved:true,period:'September 2026'},error:null};}
            if(name==='get_oclm_workspace')return {data:{revision:backend.drafts[args.p_cong_id]?.revision||0,draft:backend.drafts[args.p_cong_id]?.draft||null,publication:backend.publications['qa-live-token']?{...backend.publications['qa-live-token'],version:backend.publicationVersions[args.p_cong_id]||0,token:'qa-live-token'}:null},error:null};
            if(name==='save_oclm_workspace'){if(backend.rejectWrites)return {error:{message:'Acceptance test: save rejected'}};const old=backend.drafts[args.p_cong_id];if(args.p_expected_revision!==(old?.revision||0))return {error:{code:'40001',message:'Shared draft changed'}};const revision=(old?.revision||0)+1,draft=JSON.parse(JSON.stringify(args.p_data));backend.drafts[args.p_cong_id]={revision,draft};return {data:{revision,draft},error:null};}
            if(name==='publish_oclm_week'){if(backend.rejectWrites)return {error:{message:'Acceptance test: publication rejected'}};const old=backend.publications['qa-live-token']?.snapshot||{},draft=backend.drafts[args.p_cong_id].draft,assignments={...old.assignments};if(args.p_remove)delete assignments[args.p_week];else assignments[args.p_week]=Object.fromEntries(Object.entries(draft.assignments[args.p_week]||{}).filter(([id,a])=>!['cancelled','reassigned'].includes(a.status)).map(([id,a])=>[id,{personId:a.personId||null,customTitle:a.customTitle||''}]));const snapshot={v:2,kind:'midweek',congregation:'Acceptance Test',defaultWeek:args.p_week,publishedWeeks:Object.keys(assignments).sort(),assignments,people:draft.personnel.map(({id,name})=>({id,name})),additionalDuties:draft.additionalDuties,weekDetails:{...old.weekDetails,[args.p_week]:{additionalDuties:draft.additionalDuties,program:draft.programs?.[args.p_week]||null}}};const version=(backend.publicationVersions[args.p_cong_id]||0)+1;backend.publicationVersions[args.p_cong_id]=version;backend.publications['qa-live-token']={snapshot,updated_at:new Date().toISOString()};return {data:{version,token:'qa-live-token',snapshot,publishedAt:new Date().toISOString()},error:null};}
            if(name==='get_oclm_publication_history')return {data:[],error:null};
            if(name==='get_oclm_roster')return {data:tables.publishers.filter(p=>p.cong_id===args.p_cong_id).map(p=>({id:p.id,name:p.name,gender:p.gender,isElder:p.is_elder,isMS:p.is_ms})),error:null};
            if(name==='get_oclm_public_revision')return {data:(backend.publications[args.p_token]||window.__qaPublicationsSeed?.[args.p_token])?.updated_at||null,error:null};
            if(name==='ca_is_superadmin')return {data:backend.superadmin===true,error:null};
            if(name==='upsert_oclm_public_snapshot'){
                if(backend.rejectWrites)return {data:null,error:{message:'Acceptance test: publication rejected'}};
                const token='qa-live-token';backend.publications[token]={snapshot:JSON.parse(JSON.stringify(args.p_snapshot)),updated_at:new Date().toISOString()};return {data:{token},error:null};
            }
            if(name==='get_oclm_public_snapshot')return {data:backend.publications[args.p_token]||window.__qaPublicationsSeed?.[args.p_token]||null,error:null};
            if(name==='get_public_link_context')return {data:backend.publicLinks[args.p_token]||window.__qaPublicLinksSeed?.[args.p_token]||null,error:null};
            return { data: null, error: null };
        }
    }) };
    if(new URLSearchParams(location.search).get('cong')||new URLSearchParams(location.search).get('token')||location.hash.startsWith('#live='))return;
    if(sessionStorage.getItem('fs_auth_type')==='demo')return;
    if(sessionStorage.getItem('ca_signed_out')!=='true')for (const [key, value] of Object.entries({ fs_auth: 'true', fs_auth_type: 'admin', fs_role: 'admin', fs_cong_id: cong.id, fs_cong_name: cong.name, fs_last_activity: String(Date.now()) })) sessionStorage.setItem(key, value);
})();
