/* Capture the simplified public S-140 and real application UI with fictional demo records and an isolated backend. */
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require('playwright');const root=path.resolve(__dirname,'..'),output=path.join(root,'artifacts/demo-screens');fs.mkdirSync(output,{recursive:true});
const server=http.createServer((req,res)=>{const p=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname.replace(/^\/$/,'/index.html'));if(!p.startsWith(root+path.sep)||!fs.existsSync(p)){res.writeHead(404).end();return;}res.setHeader('Content-Type',p.endsWith('.js')?'application/javascript':p.endsWith('.css')?'text/css':'text/html');fs.createReadStream(p).pipe(res);});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch();
for(const [device,width,height,mobile] of [['desktop',1440,1000,false],['tablet',820,1180,true],['phone',390,844,true]]){const context=await browser.newContext({viewport:{width,height},isMobile:mobile,hasTouch:mobile,serviceWorkers:'block'});await context.route('**/*.supabase.co/**',r=>r.abort());await context.route('**/npm/@supabase/supabase-js@2',r=>r.fulfill({contentType:'application/javascript',body:'/* isolated demo backend */'}));await context.addInitScript(()=>{window.__CA_DEMO_CAPTURE=true;});await context.addInitScript({path:path.join(__dirname,'browser-fixture.js')});const page=await context.newPage();await page.goto(`http://127.0.0.1:${server.address().port}`);await page.waitForFunction(()=>window.db?.publishers.length===1000&&window.initMidweekScheduler);await page.evaluate(()=>{window.currentCongId='demo-cong';sessionStorage.setItem('fs_cong_id','demo-cong');sessionStorage.setItem('fs_cong_name','Demo Congregation');window.db.currentCongData={id:'demo-cong',name:'Demo Congregation',status:'active',feature_oclm:true,feature_attendance:true};for(const id of ['nav-cong-name','ca-topbar-name']){const el=document.getElementById(id);if(el)el.textContent='Demo Congregation';}window.ui.switchTab('oclm');window.initMidweekScheduler();window.setSchedulerWeek('2026-W41');});await page.locator('#autoRemaining').click();await page.evaluate(()=>{for(const [id,value] of Object.entries({meetingStartTime:'19:00',meetingOpeningSong:'',meetingMiddleSong:'',meetingClosingSong:''}))document.getElementById(id).value=value;window.saveMeetingDetails();});
await page.evaluate(()=>{const roster=window.MidweekScheduler.getDraft().personnel;window.db.publishers=roster.map((p,i)=>({...window.__qaBackend.tables.publishers[i],id:'demo-'+p.id,cong_id:'demo-cong',name:p.name,phone:'',address:'',emergency_phone:''}));window.__qaBackend.tables.publishers=window.db.publishers;});
for(const [topic,tab] of [['records','publishers'],['attendance','attendance'],['schedule','oclm']]){await page.evaluate(tab=>window.ui.switchTab(tab),tab);if(topic==='schedule'){await page.locator('#reviewScheduleBtn').click();await page.waitForTimeout(200);await page.locator('#publishWeekBtn').scrollIntoViewIfNeeded();await page.waitForTimeout(700);await page.addStyleTag({content:'#demo-session-banner{display:none!important}'});await page.screenshot({path:path.join(output,`${device}-review-publish.jpg`),type:'jpeg',quality:86});await page.evaluate(async()=>{const payload=window.MidweekScheduler.getPayload(['2026-W41']);window.__qaBackend.publications['demo-preview']={snapshot:payload,updated_at:new Date().toISOString()};history.replaceState(null,'','?mode=oclm&token=demo-preview');await window.PublicLinks.boot();scrollTo(0,0);});}if(topic==='attendance'){await page.evaluate(()=>{const sy=Number(document.getElementById('att-year').value),month=Number(document.getElementById('att-month').value);window.db.attendance=[{id:`demo-cong_${sy}_${month}`,service_year:sy,month,w1_mid:'84',w1_end:'102',w2_mid:'88',w2_end:'106'}];document.getElementById('att-cong-name').value='Demo Congregation';window.ui.renderAttendance();});}await page.evaluate(()=>{scrollTo(0,0);const main=document.querySelector('.main-content');if(main)main.scrollTop=0;});await page.waitForTimeout(4500);assert(!(await page.locator('body').innerText()).includes('Acceptance Test'),'Demo label still contains the test workspace');await page.addStyleTag({content:'#demo-session-banner{display:none!important}'});await page.screenshot({path:path.join(output,`${device}-${topic}.jpg`),type:'jpeg',quality:86});}await context.close();}
await browser.close();console.log('PASS nine real software screenshots use Demo Congregation and fictional records; all production API requests blocked');})().catch(e=>{console.error(e.message);process.exitCode=1}).finally(()=>{server.close();process.exit(process.exitCode||0);});
