begin;
create schema ca_roster_check;
create function ca_roster_check.assert(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAILED: %',label;end if;end $$;
grant usage on schema ca_roster_check to authenticated;grant execute on function ca_roster_check.assert(boolean,text) to authenticated;
insert into public.congregations(id,name,status) values('roster-check-a','Roster A','active'),('roster-check-b','Roster B','active');
insert into public.publishers(id,cong_id,name,service_group,phone,address) values('roster-a1','roster-check-a','Sample A','One','SECRET PHONE','SECRET ADDRESS'),('roster-a2','roster-check-a','Sample B','Two','SECRET','SECRET'),('roster-b1','roster-check-b','Sample C','One','SECRET','SECRET');
insert into public.congregation_access(cong_id,email,role,service_group) values('roster-check-a','oclm-roster@example.com','oclm',null),('roster-check-a','group-roster@example.com','group_overseer','One');
set request.jwt.claims='{"email":"oclm-roster@example.com","app_metadata":{"provider":"google"}}';set role authenticated;
select ca_roster_check.assert(jsonb_array_length(public.get_oclm_roster('roster-check-a'))=2,'OCLM roster includes all publisher names');
select ca_roster_check.assert(public.get_oclm_roster('roster-check-a')::text not like '%SECRET%','OCLM roster omits contacts and addresses');
select ca_roster_check.assert((select count(*)=0 from public.publishers),'OCLM cannot read private publisher rows');
do $$begin begin perform public.get_oclm_roster('roster-check-b');raise exception 'Other congregation roster allowed';exception when insufficient_privilege then null;end;begin perform public.save_group_reports('roster-check-a',2027,9,'[]');raise exception 'OCLM saved reports';exception when insufficient_privilege then null;end;end $$;
reset role;set request.jwt.claims='{"email":"group-roster@example.com","app_metadata":{"provider":"google"}}';set role authenticated;
select ca_roster_check.assert(jsonb_array_length(public.save_group_reports('roster-check-a',2027,9,'[{"pub_id":"roster-a1","shared_in_ministry":true,"studies":2,"hours":10,"comments":"Group entry"}]'))=1,'group overseer edits own report');
do $$begin begin perform public.save_group_reports('roster-check-a',2027,9,'[{"pub_id":"roster-a1","studies":99},{"pub_id":"roster-a2","studies":3}]');raise exception 'Other group allowed';exception when insufficient_privilege then null;end;begin perform public.save_group_reports('roster-check-b',2027,9,'[{"pub_id":"roster-b1"}]');raise exception 'Other congregation allowed';exception when insufficient_privilege then null;end;end $$;
select ca_roster_check.assert((select studies=2 from public.reports where pub_id='roster-a1'),'rejected mixed batch is atomic');
reset role;update public.congregation_access set active=false where email='group-roster@example.com';set role authenticated;
do $$begin begin perform public.save_group_reports('roster-check-a',2027,9,'[]');raise exception 'Revoked group edited';exception when insufficient_privilege then null;end;end $$;
reset role;rollback;
select 'PASS limited OCLM roster, atomic group bulk, group/tenant boundaries and immediate revocation' as result;
