begin;
insert into auth.users(id,email,email_confirmed_at,raw_app_meta_data) values('30986ed0-5d1d-4519-942c-b6825fdd57d1','mail-test@example.invalid',now(),'{"provider":"google"}');
set request.jwt.claims='{"sub":"30986ed0-5d1d-4519-942c-b6825fdd57d1","email":"mail-test@example.invalid","role":"authenticated","app_metadata":{"provider":"google"}}';set local role authenticated;
select public.request_congregation_trial('Fictional Mail Test',true);
select public.request_congregation_trial('Fictional Mail Test',true);
do $$begin begin perform public.get_trial_requests();raise exception 'Nonowner read requests';exception when insufficient_privilege then null;end;begin perform public.claim_transactional_mail();raise exception 'User claimed mail';exception when insufficient_privilege then null;end;end $$;
reset role;
do $$begin if(select count(*) from ca_private.trial_requests where email='mail-test@example.invalid')<>1 or(select count(*) from ca_private.mail_outbox where email='mail-test@example.invalid')<>1 then raise exception 'Request/ack dedupe failed';end if;end $$;
insert into public.congregations(id,name,status) values('mail-test','Fictional Mail Test','active');
insert into public.congregation_access(cong_id,email,role) values('mail-test','mail-test@example.invalid','admin');
do $$begin if not exists(select 1 from ca_private.trial_requests where email='mail-test@example.invalid' and status='approved' and cong_id='mail-test') then raise exception 'Provisioning did not approve request';end if;if(select count(*) from ca_private.mail_outbox where email='mail-test@example.invalid')<>2 then raise exception 'Welcome email not queued';end if;end $$;
set local role authenticated;
select public.set_workspace_email('mail-test','mail-test@example.invalid',true,true,true,true,1,'09:00','Asia/Kolkata');
do $$begin begin perform public.set_workspace_email('mail-test','unverified@example.invalid',true,true,true,true,1,'09:00','Asia/Kolkata');raise exception 'Unverified email accepted';exception when raise_exception then if sqlerrm='Unverified email accepted' then raise;end if;end;begin perform public.get_workspace_email('other-workspace');raise exception 'Cross-congregation mail settings read';exception when insufficient_privilege then null;end;end $$;
reset role;
set request.jwt.claims='{"role":"service_role"}';set local role service_role;
select public.claim_transactional_mail();
reset role;
do $$declare job ca_private.mail_outbox;begin select * into job from ca_private.mail_outbox where email='mail-test@example.invalid' and state='sending' limit 1;if job.id is null then raise exception 'Worker failed to claim mail';end if;if public.finish_transactional_mail(job.id,gen_random_uuid(),'wrong receipt') then raise exception 'Wrong lease accepted';end if;if not public.finish_transactional_mail(job.id,job.lease,'test-provider-receipt') then raise exception 'Delivery receipt not stored';end if;if public.finish_transactional_mail(job.id,job.lease,'duplicate') then raise exception 'Duplicate receipt accepted';end if;end $$;
rollback;
