begin;
create schema ca_att_check;
create function ca_att_check.assert(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAILED: %',label;end if;end $$;
grant usage on schema ca_att_check to anon,authenticated;grant execute on function ca_att_check.assert(boolean,text) to anon,authenticated;
insert into public.congregations(id,name,status) values('attendance-check-a','Calendar A','active'),('attendance-check-b','Calendar B','active');
insert into public.congregation_access(cong_id,email,role) values('attendance-check-a','calendar-a@example.com','attendance'),('attendance-check-a','oclm-calendar@example.com','oclm');
insert into public.ca_public_links(cong_id,kind) values('attendance-check-a','attendance');
select set_config('ca_att_check.token',(select token::text from public.ca_public_links where cong_id='attendance-check-a'),true);
select set_config('ca_att_check.date',(now() at time zone 'Asia/Kolkata')::date::text,true);
set request.jwt.claims='{"email":"calendar-a@example.com","app_metadata":{"provider":"google"}}';set role authenticated;
select public.save_meeting_calendar('attendance-check-a','Asia/Kolkata',3,0,current_setting('ca_att_check.date')::date,'midweek');
select ca_att_check.assert(public.get_attendance_calendar('attendance-check-a')->'settings'->>'timezone'='Asia/Kolkata','attendance overseer sets calendar');
do $$begin begin perform public.get_attendance_calendar('attendance-check-b');raise exception 'Other tenant calendar visible';exception when insufficient_privilege then null;end;end $$;
reset role;set request.jwt.claims='{"email":"oclm-calendar@example.com","app_metadata":{"provider":"google"}}';set role authenticated;
do $$begin begin perform public.save_meeting_calendar('attendance-check-a','UTC',2,6);raise exception 'OCLM changed attendance';exception when insufficient_privilege then null;end;end $$;
select ca_att_check.assert((select count(*)=0 from public.ca_memorial_attendance),'OCLM cannot read Memorial history');
reset role;set role anon;
select ca_att_check.assert(public.get_attendance_meeting(current_setting('ca_att_check.token'))->>'kind'='midweek','server resolves current meeting');
select public.submit_current_attendance(current_setting('ca_att_check.token'),current_setting('ca_att_check.date')::date,84);
do $$begin begin perform public.submit_current_attendance(current_setting('ca_att_check.token'),current_setting('ca_att_check.date')::date-1,88);raise exception 'Changed date accepted';exception when raise_exception then if sqlerrm='Changed date accepted' then raise;end if;end;begin perform public.submit_public_attendance(current_setting('ca_att_check.token'),1900,0,'{"w5_end":"999"}');raise exception 'Changed period accepted';exception when raise_exception then if sqlerrm='Changed period accepted' then raise;end if;end;begin perform public.submit_current_attendance(current_setting('ca_att_check.token'),current_setting('ca_att_check.date')::date,-1);raise exception 'Negative count accepted';exception when raise_exception then if sqlerrm='Negative count accepted' then raise;end if;end;end $$;
reset role;
select ca_att_check.assert((select count(*)=1 from public.meeting_attendance where cong_id='attendance-check-a'),'only current attendance period is written');
select ca_att_check.assert((select service_year=extract(year from current_setting('ca_att_check.date')::date)::integer+case when extract(month from current_setting('ca_att_check.date')::date)>=9 then 1 else 0 end from public.meeting_attendance where cong_id='attendance-check-a'),'service year uses September boundary');
update public.ca_meeting_calendar set kind='CA' where cong_id='attendance-check-a';set role anon;
select ca_att_check.assert(not (public.get_attendance_meeting(current_setting('ca_att_check.token'))->>'canSubmit')::boolean,'Circuit assembly has no attendance form');
do $$begin begin perform public.submit_current_attendance(current_setting('ca_att_check.token'),current_setting('ca_att_check.date')::date,99);raise exception 'Assembly count accepted';exception when raise_exception then if sqlerrm='Assembly count accepted' then raise;end if;end;end $$;
reset role;update public.ca_meeting_calendar set kind='RC' where cong_id='attendance-check-a';set role anon;
select ca_att_check.assert(not (public.get_attendance_meeting(current_setting('ca_att_check.token'))->>'canSubmit')::boolean,'Regional convention has no attendance form');
reset role;update public.ca_meeting_calendar set kind='Memorial' where cong_id='attendance-check-a';set role anon;
select public.submit_current_attendance(current_setting('ca_att_check.token'),current_setting('ca_att_check.date')::date,150);
reset role;
select ca_att_check.assert((select attendance=150 from public.ca_memorial_attendance where cong_id='attendance-check-a'),'Memorial stored separately');
set request.jwt.claims='{"email":"calendar-a@example.com","app_metadata":{"provider":"google"}}';set role authenticated;
select public.save_memorial_attendance('attendance-check-a','2026-04-02',149);
select ca_att_check.assert(jsonb_array_length(public.get_attendance_calendar('attendance-check-a')->'memorials')=2,'Memorial history retained by date and service year');
reset role;update public.ca_public_links set active=false where cong_id='attendance-check-a';set role anon;
do $$begin begin perform public.get_attendance_meeting(current_setting('ca_att_check.token'));raise exception 'Withdrawn link accepted';exception when insufficient_privilege then null;end;begin perform * from public.ca_memorial_attendance;raise exception 'Anonymous Memorial read accepted';exception when insufficient_privilege then null;end;end $$;
reset role;rollback;
select 'PASS server attendance context, rejected forged period/date, CA/RC exclusions, separate Memorial history, role and congregation isolation' as result;
