\set ON_ERROR_STOP on
-- Synthetic records in the isolated database only. All test mutations roll back.
begin;
insert into public.publishers(id,cong_id,name,gender) values('department-a-1','a','Sample department publisher','Male'),('department-a-2','a','Another sample publisher','Male'),('department-b-1','b','Other congregation publisher','Male');
insert into public.congregation_access(cong_id,email,role) values('a','av-a@example.com','av'),('a','attendant-a@example.com','attendant');
create function test.department_denied(query text) returns void language plpgsql security invoker as $$begin execute query;raise exception 'FAILED: action was permitted';exception when insufficient_privilege then null;end $$;
grant execute on function test.department_denied(text) to authenticated;
set request.jwt.claims='{"sub":"10000000-0000-0000-0000-000000000001","email":"av-a@example.com","app_metadata":{"provider":"google"}}';set role authenticated;
select test.assert((public.get_department_workspace('a','av')->'people') @> '[{"id":"department-a-1"}]','AV sees congregation names');
select test.assert(not (public.get_department_workspace('a','av')->'people') @> '[{"id":"department-b-1"}]','roster excludes another congregation');
select test.assert((select count(*)=0 from public.reports),'AV cannot read reports');
select test.department_denied($q$select public.get_department_workspace('b','av')$q$);
select test.department_denied($q$select public.get_department_workspace('a','attendant')$q$);
select public.request_department_person('a','av','department-a-1');
select test.department_denied($q$select public.decide_department_person('a','av','department-a-1',true)$q$);
do $$begin perform public.save_department_duty('a','av',(public.get_department_workspace('a','av')->>'revision')::bigint,null,'Invalid places',null,true);raise exception 'FAILED null places accepted';exception when raise_exception then if SQLERRM not like 'Enter a duty name%' then raise;end if;end $$;
select public.save_department_duty('a','av',(public.get_department_workspace('a','av')->>'revision')::bigint,null,'Sample Audio',1,true);
select test.department_denied(format('select public.save_department_assignments(''a'',''av'',%s,''2026-W43'',%L::jsonb)',(public.get_department_workspace('a','av')->>'revision'),jsonb_build_object((public.get_department_workspace('a','av')->'duties'->0->>'id')||'_1','department-a-1')));
reset role;
set request.jwt.claims='{"sub":"10000000-0000-0000-0000-000000000002","email":"admin-a@example.com","app_metadata":{"provider":"google"}}';set role authenticated;
select public.decide_department_person('a','av','department-a-1',true);
reset role;
set request.jwt.claims='{"sub":"10000000-0000-0000-0000-000000000001","email":"av-a@example.com","app_metadata":{"provider":"google"}}';set role authenticated;
select public.save_department_assignments('a','av',(public.get_department_workspace('a','av')->>'revision')::bigint,'2026-W43',jsonb_build_object((public.get_department_workspace('a','av')->'duties'->0->>'id')||'_1','department-a-1'));
select test.assert((public.get_department_workspace('a','av')->'assignments'->'2026-W43')::text like '%Sample department publisher%','approved assignment saved with name');
do $$begin perform public.save_department_assignments('a','av',0,'2026-W43','{}');raise exception 'FAILED stale revision accepted';exception when serialization_failure then null;end $$;
reset role;
set request.jwt.claims='{"sub":"10000000-0000-0000-0000-000000000003","email":"attendant-a@example.com","app_metadata":{"provider":"google"}}';set role authenticated;
select public.save_department_duty('a','attendant',(public.get_department_workspace('a','attendant')->>'revision')::bigint,null,'Entrance',2,true);
select test.department_denied($q$select public.get_oclm_workspace('a')$q$);
reset role;
set request.jwt.claims='{"sub":"10000000-0000-0000-0000-000000000002","email":"admin-a@example.com","app_metadata":{"provider":"google"}}';set role authenticated;
select test.assert((public.get_oclm_workspace('a')->'draft'->'assignments'->'2026-W43')::text like '%department-a-1%','OCLM receives department assignment');
select public.save_oclm_workspace('a',(public.get_oclm_workspace('a')->>'revision')::bigint,public.get_oclm_workspace('a')->'draft');
select test.department_denied(format('select public.save_oclm_workspace(''a'',%s,%L::jsonb)',(public.get_oclm_workspace('a')->>'revision'),jsonb_set(public.get_oclm_workspace('a')->'draft','{assignments,2026-W43}','{}')));
select public.publish_oclm_week('a','2026-W43',(public.get_oclm_workspace('a')->>'revision')::bigint,coalesce((public.get_oclm_workspace('a')->'publication'->>'version')::bigint,0));
select test.assert((public.get_oclm_workspace('a')->'publication'->'snapshot'->'people') @> '[{"id":"department-a-1","name":"Sample department publisher"}]','published duty includes approved name');
select test.assert((public.get_oclm_workspace('a')->'publication'->'snapshot'->'weekDetails'->'2026-W43'->'additionalDuties')::text like '%Sample Audio%','published week includes duty definition');
select set_config('ca.department_test_backup',public.export_congregation_workspace('a')::text,true);
select public.decide_department_person('a','av','department-a-1',false);
select public.restore_congregation_workspace('a',public.export_congregation_workspace('a')->>'fingerprint',current_setting('ca.department_test_backup')::jsonb->'data');
select test.assert((public.get_department_workspace('a','av')->'people') @> '[{"id":"department-a-1","status":"approved"}]','backup restores department eligibility');
select public.decide_department_person('a','av','department-a-1',false);
reset role;
set request.jwt.claims='{"sub":"10000000-0000-0000-0000-000000000001","email":"av-a@example.com","app_metadata":{"provider":"google"}}';set role authenticated;
select test.department_denied(format('select public.save_department_assignments(''a'',''av'',%s,''2026-W44'',%L::jsonb)',(public.get_department_workspace('a','av')->>'revision'),jsonb_build_object((public.get_department_workspace('a','av')->'duties'->0->>'id')||'_1','department-a-1')));
reset role;
update public.congregation_access set active=false where email='av-a@example.com';set role authenticated;
select test.department_denied($q$select public.get_department_workspace('a','av')$q$);
reset role;rollback;
\echo PASS department isolation, approvals, revision conflicts, protected OCLM slots, publication, revocation and backup recovery
