-- FICTIONAL ACCEPTANCE DATABASE ONLY. Never run acceptance scripts in a real project.
reset role;
insert into public.congregations(id,name,email,status) values('fictional-legacy-adoption','Fictional legacy adoption','legacy-admin@example.com','active');
insert into public.congregation_access(cong_id,email,role) values('fictional-legacy-adoption','legacy-admin@example.com','admin');
insert into public.publishers(id,cong_id,name) values('fictional-legacy-person','fictional-legacy-adoption','Fictional Legacy Publisher');
insert into ca_private.department_duties(cong_id,department,id) values('fictional-legacy-adoption','av','Duty_abcdefabcdefabcdefabcdefabcdefab');
insert into ca_private.department_people(cong_id,department,publisher_id,status) values('fictional-legacy-adoption','av','fictional-legacy-person','approved');
insert into public.ca_oclm_workspaces(cong_id,revision,data) values('fictional-legacy-adoption',19,'{"v":3,"personnel":[{"id":"legacy-scheduler-id","publisherId":"fictional-legacy-person","name":"Fictional Legacy Publisher","roles":[],"availability":[]}],"assignments":{"2026-W42":{"Duty_abcdefabcdefabcdefabcdefabcdefab_1":{"personId":"legacy-scheduler-id","status":"scheduled"}}},"additionalDuties":[{"id":"Duty_abcdefabcdefabcdefabcdefabcdefab","section":"Audio Video Department","name":"Audio","slots":1,"enabled":true}],"programs":{},"template":"modern"}'::jsonb);
insert into public.ca_oclm_publications(cong_id,token,version,snapshot) values('fictional-legacy-adoption','10000000-1111-2222-3333-000000000001',9,'{"v":2,"kind":"midweek","publishedWeeks":["2026-W42"],"assignments":{"2026-W42":{"Duty_abcdefabcdefabcdefabcdefabcdefab_1":{"personId":"legacy-scheduler-id","status":"scheduled"}}},"people":[{"id":"legacy-scheduler-id","name":"Fictional Legacy Publisher"}]}'::jsonb);
insert into ca_private.department_publications(cong_id,department,week,version,snapshot) values('fictional-legacy-adoption','av','2026-W42',4,'{"duties":[{"id":"Duty_abcdefabcdefabcdefabcdefabcdefab","section":"Audio Video Department","name":"Audio","slots":1,"enabled":true}],"assignments":{"Duty_abcdefabcdefabcdefabcdefabcdefab_1":{"personId":"legacy-scheduler-id","status":"scheduled"}},"people":[{"id":"legacy-scheduler-id","name":"Fictional Legacy Publisher"}]}'::jsonb);
