const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto');
const {chromium,webkit}=require('playwright');const root=path.resolve(__dirname,'..');const output=process.env.CA_SITE_OUTPUT?path.resolve(process.env.CA_SITE_OUTPUT):path.join(root,'artifacts');fs.mkdirSync(output,{recursive:true});
const server=http.createServer((req,res)=>{const relative=new URL(req.url,'http://localhost').pathname,file=path.resolve(root,'.'+(relative==='/'?'/index.html':relative));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.writeHead(404).end();return;}res.setHeader('Content-Type',file.endsWith('.css')?'text/css':file.endsWith('.js')?'application/javascript':'text/html');res.end(fs.readFileSync(file));});
const digest=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
(async()=>{
 const published=process.env.CA_SITE_URL;if(published){let ready=false;for(let i=0;i<40&&!ready;i++){const checks=await Promise.all(['index.html','site.css','site.js','how-to-use.html','guide.js'].map(async name=>{const response=await fetch(new URL(name,published),{headers:{'Cache-Control':'no-cache'},signal:AbortSignal.timeout(15000)});return response.ok&&digest(Buffer.from(await response.arrayBuffer()))===digest(fs.readFileSync(path.join(root,name)));}));ready=checks.every(Boolean);if(!ready)await new Promise(r=>setTimeout(r,15000));}assert(ready,'Published site differs from this commit');console.log('PASS public website deployment matches this commit');}
 else await new Promise(r=>server.listen(0,'127.0.0.1',r));
 for(const [name,engine,viewport,mobile] of [['desktop',chromium,{width:1440,height:1000},false],['mobile-chromium',chromium,{width:390,height:844},true],['mobile-webkit',webkit,{width:375,height:812},true]]){
  const browser=await engine.launch(),context=await browser.newContext({viewport,isMobile:mobile,hasTouch:mobile}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await context.route('**/formsubmit.co/**',route=>route.abort());
  await page.goto(published||`http://localhost:${server.address().port}`);assert.equal(await page.locator('h1').count(),1);assert.match(await page.locator('.price').innerText(),/1,499/);
  assert(await page.locator('.hero-actions a').first().getAttribute('href')==='#start');
  const previewTabs=await page.locator('[data-preview]').evaluateAll(tabs=>tabs.map(tab=>tab.dataset.preview));
  assert.deepEqual(previewTabs,['records','attendance','schedule'],'Preview tabs must be unique and appear once');
  for(const tab of ['attendance','schedule','records']){await page.locator('[data-preview="'+tab+'"]').click();assert.equal(await page.locator('[data-preview="'+tab+'"]').getAttribute('aria-selected'),'true');assert(await page.locator('#preview-screen').innerText());}
  await page.locator('[data-preview="records"]').focus();await page.keyboard.press('ArrowRight');assert.equal(await page.locator('[data-preview="attendance"]').getAttribute('aria-selected'),'true');
  if(mobile){for(const width of [320,375,390,430]){await page.setViewportSize({width,height:viewport.height});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Website overflows '+width);}await page.setViewportSize(viewport);await page.locator('#menu-toggle').click();assert(await page.locator('#mobile-menu').isVisible());await page.keyboard.press('Escape');assert.equal(await page.locator('#mobile-menu').isVisible(),false);}
  const anchors=await page.locator('a[href^="#"]').evaluateAll(items=>items.map(el=>el.getAttribute('href')));for(const href of anchors)if(href!=='#')assert(await page.locator(href).count(),'Broken page anchor '+href);
  await page.locator('.faq summary').first().click();assert(await page.locator('.faq details').first().getAttribute('open')!==null);
  await page.locator('[name="name"]').fill('Sample Contact');await page.locator('[name="congregation"]').fill('Example Congregation');await page.locator('[name="email"]').fill('example@example.com');await page.locator('[name="authorized"]').check();await page.locator('#trial-form button[type="submit"]').click();assert(await page.locator('#request-result').isVisible());const email=await page.locator('#email-request').getAttribute('href');assert(email.startsWith('mailto:'));assert(decodeURIComponent(email).includes('30-day'));assert(!await page.locator('iframe').count(),'Request silently submits to a third party');
  await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(300);await page.screenshot({path:path.join(output,name+'-hero.png')});await page.locator('#pricing').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(output,name+'-pricing.png')});await page.locator('#start').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(output,name+'-trial.png')});const guideURL=new URL('how-to-use.html#midweek',page.url()).href;await page.goto(guideURL);
  assert.equal(await page.locator('h1').count(),1);assert.equal(await page.locator('#guide-tab-midweek').getAttribute('aria-selected'),'true');
  const topics=['start','publishers','reports','attendance','midweek','sharing','backup'];
  for(const topic of topics){await page.locator('#guide-tab-'+topic).click();assert.equal(await page.locator('#guide-'+topic).isVisible(),true);assert.equal(await page.locator('[role="tabpanel"]:visible').count(),1);assert(await page.locator('#guide-'+topic+' li').count()>=4);}
  await page.locator('#guide-tab-start').focus();await page.keyboard.press('ArrowRight');assert.equal(await page.locator('#guide-tab-publishers').getAttribute('aria-selected'),'true');
  await page.reload();assert.equal(await page.locator('#guide-tab-publishers').getAttribute('aria-selected'),'true');
  if(mobile){for(const width of [320,375,390,430]){await page.setViewportSize({width,height:viewport.height});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Help guide overflows '+width);}await page.setViewportSize(viewport);}
  await page.locator('#guide-tab-midweek').click();await page.screenshot({path:path.join(output,name+'-usage-guide.png')});
  assert.deepEqual(errors,[]);console.log('PASS',name,': responsive widths, mobile menu, preview tabs/keyboard, pricing, FAQ, anchors, trial draft and no automatic sending');await browser.close();
 }
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>server.close());
